project_name: infraspec

version: 2

release:
  github:
    owner: robmorgan
    name: infraspec
  draft: false
  prerelease: false

builds:
  - id: infraspec
    main: ./cmd/infraspec/main.go
    binary: infraspec
    ldflags:
      - -s -w -X github.com/robmorgan/infraspec/internal/build.Version={{.Version}}
      - -X github.com/robmorgan/infraspec/internal/build.Commit={{.Commit}}
      - -X github.com/robmorgan/infraspec/internal/build.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{.Env.MACOS_SIGN_P12}}"
        password: "{{.Env.MACOS_SIGN_PASSWORD}}"
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"
        key: "{{.Env.MACOS_NOTARY_KEY}}"
        wait: true
        timeout: 30m

archives:
  - id: archive
    ids:
      - infraspec
    files:
      - LICENSE
      - README.md
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: ["tar.gz"]
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

changelog:
  use: github

homebrew_casks:
  - repository:
      owner: robmorgan
      name: homebrew-infraspec
    homepage: https://infraspec.sh
    description: Test your cloud infrastructure in plain English, no code required.
    license: Apache License 2.0

announce:
  slack:
    enabled: true
    message_template: ":tada: infraspec {{.Tag}} is now available!!!! :tada:"
    channel: "#infraspec"
    username: "infraspecbot"
