// Code generated by CloudMirror from AWS Smithy models. DO NOT EDIT.
// Source: /Users/robbym/.cloudmirror/api-models-aws/models/sqs/service/2012-11-05/sqs-2012-11-05.json
// Service: sqs
// Protocol: json
// Generated: 2025-12-18T03:13:19Z

package sqs

// Enum type aliases

type MessageSystemAttributeName string

type QueueAttributeName string

// CancelMessageMoveTaskResult represents the CancelMessageMoveTaskResult structure.
type CancelMessageMoveTaskResult struct {
	ApproximateNumberOfMessagesMoved *int64 `json:"ApproximateNumberOfMessagesMoved,omitempty"` // The approximate number of messages already moved to the destination queue.
}

// ChangeMessageVisibilityBatchResult For each message in the batch, the response contains a ` ChangeMessageVisibilityBatchResultEntry ...
type ChangeMessageVisibilityBatchResult struct {
	Failed     []BatchResultErrorEntry                   `json:"Failed,omitempty"`     // A list of ` BatchResultErrorEntry ` items.
	Successful []ChangeMessageVisibilityBatchResultEntry `json:"Successful,omitempty"` // A list of ` ChangeMessageVisibilityBatchResultEntry ` items.
}

// CreateQueueResult Returns the `QueueUrl` attribute of the created queue.
type CreateQueueResult struct {
	QueueUrl *string `json:"QueueUrl,omitempty"` // The URL of the created Amazon SQS queue.
}

// DeleteMessageBatchResult For each message in the batch, the response contains a ` DeleteMessageBatchResultEntry ` tag if t...
type DeleteMessageBatchResult struct {
	Failed     []BatchResultErrorEntry         `json:"Failed,omitempty"`     // A list of ` BatchResultErrorEntry ` items.
	Successful []DeleteMessageBatchResultEntry `json:"Successful,omitempty"` // A list of ` DeleteMessageBatchResultEntry ` items.
}

// GetQueueAttributesResult A list of returned queue attributes.
type GetQueueAttributesResult struct {
	Attributes map[string]string `json:"Attributes,omitempty"` // A map of attributes to their respective values.
}

// GetQueueUrlResult For more information, see Interpreting Responses in the Amazon SQS Developer Guide.
type GetQueueUrlResult struct {
	QueueUrl *string `json:"QueueUrl,omitempty"` // The URL of the queue.
}

// ListDeadLetterSourceQueuesResult A list of your dead letter source queues.
type ListDeadLetterSourceQueuesResult struct {
	NextToken *string  `json:"NextToken,omitempty"` // Pagination token to include in the next request. Token value is `null` if there are no additional...
	queueUrls []string `json:"queueUrls,omitempty"` // A list of source queue URLs that have the `RedrivePolicy` queue attribute configured with a dead-...
}

// ListMessageMoveTasksResult represents the ListMessageMoveTasksResult structure.
type ListMessageMoveTasksResult struct {
	Results []ListMessageMoveTasksResultEntry `json:"Results,omitempty"` // A list of message movement tasks and their attributes.
}

// ListQueueTagsResult represents the ListQueueTagsResult structure.
type ListQueueTagsResult struct {
	Tags map[string]string `json:"Tags,omitempty"` // The list of all tags added to the specified queue.
}

// ListQueuesResult A list of your queues.
type ListQueuesResult struct {
	NextToken *string  `json:"NextToken,omitempty"` // Pagination token to include in the next request. Token value is `null` if there are no additional...
	QueueUrls []string `json:"QueueUrls,omitempty"` // A list of queue URLs, up to 1,000 entries, or the value of `MaxResults` that you sent in the requ...
}

// ReceiveMessageResult A list of received messages.
type ReceiveMessageResult struct {
	Messages []Message `json:"Messages,omitempty"` // A list of messages.
}

// SendMessageBatchResult For each message in the batch, the response contains a ` SendMessageBatchResultEntry ` tag if the...
type SendMessageBatchResult struct {
	Failed     []BatchResultErrorEntry       `json:"Failed,omitempty"`     // A list of ` BatchResultErrorEntry ` items with error details about each message that can't be enq...
	Successful []SendMessageBatchResultEntry `json:"Successful,omitempty"` // A list of ` SendMessageBatchResultEntry ` items.
}

// SendMessageResult The `MD5OfMessageBody` and `MessageId` elements.
type SendMessageResult struct {
	MD5OfMessageAttributes       *string `json:"MD5OfMessageAttributes,omitempty"`       // An MD5 digest of the non-URL-encoded message attribute string. You can use this attribute to veri...
	MD5OfMessageBody             *string `json:"MD5OfMessageBody,omitempty"`             // An MD5 digest of the non-URL-encoded message body string. You can use this attribute to verify th...
	MD5OfMessageSystemAttributes *string `json:"MD5OfMessageSystemAttributes,omitempty"` // An MD5 digest of the non-URL-encoded message system attribute string. You can use this attribute ...
	MessageId                    *string `json:"MessageId,omitempty"`                    // An attribute containing the `MessageId` of the message sent to the queue. For more information, s...
	SequenceNumber               *string `json:"SequenceNumber,omitempty"`               // This parameter applies only to FIFO (first-in-first-out) queues. The large, non-consecutive numbe...
}

// StartMessageMoveTaskResult represents the StartMessageMoveTaskResult structure.
type StartMessageMoveTaskResult struct {
	TaskHandle *string `json:"TaskHandle,omitempty"` // An identifier associated with a message movement task. You can use this identifier to cancel a sp...
}

// AddPermissionRequest represents the AddPermissionRequest structure.
type AddPermissionRequest struct {
	AWSAccountIds []string `json:"AWSAccountIds,omitempty"` // The Amazon Web Services account numbers of the principals who are to receive permission. For info...
	Actions       []string `json:"Actions,omitempty"`       // The action the client wants to allow for the specified principal. Valid values: the name of any a...
	Label         *string  `json:"Label,omitempty"`         // The unique identification of the permission you're setting (for example, `AliceSendMessage`). Max...
	QueueUrl      *string  `json:"QueueUrl,omitempty"`      // The URL of the Amazon SQS queue to which permissions are added. Queue URLs and names are case-sen...
}

// BatchResultErrorEntry Gives a detailed description of the result of an action on each entry in the request.
type BatchResultErrorEntry struct {
	Code        *string `json:"Code,omitempty"`        // An error code representing why the action failed on this entry.
	Id          *string `json:"Id,omitempty"`          // The `Id` of an entry in a batch request.
	Message     *string `json:"Message,omitempty"`     // A message explaining why the action failed on this entry.
	SenderFault *bool   `json:"SenderFault,omitempty"` // Specifies whether the error happened due to the caller of the batch API action.
}

// CancelMessageMoveTaskRequest represents the CancelMessageMoveTaskRequest structure.
type CancelMessageMoveTaskRequest struct {
	TaskHandle *string `json:"TaskHandle,omitempty"` // An identifier associated with a message movement task.
}

// ChangeMessageVisibilityBatchRequest represents the ChangeMessageVisibilityBatchRequest structure.
type ChangeMessageVisibilityBatchRequest struct {
	Entries  []ChangeMessageVisibilityBatchRequestEntry `json:"Entries,omitempty"`  // Lists the receipt handles of the messages for which the visibility timeout must be changed.
	QueueUrl *string                                    `json:"QueueUrl,omitempty"` // The URL of the Amazon SQS queue whose messages' visibility is changed. Queue URLs and names are c...
}

// ChangeMessageVisibilityBatchRequestEntry Encloses a receipt handle and an entry ID for each message in ` ChangeMessageVisibilityBatch.`
type ChangeMessageVisibilityBatchRequestEntry struct {
	Id                *string `json:"Id,omitempty"`                // An identifier for this particular receipt handle used to communicate the result. The `Id`s of a b...
	ReceiptHandle     *string `json:"ReceiptHandle,omitempty"`     // A receipt handle.
	VisibilityTimeout *int32  `json:"VisibilityTimeout,omitempty"` // The new value (in seconds) for the message's visibility timeout.
}

// ChangeMessageVisibilityBatchResultEntry Encloses the `Id` of an entry in ` ChangeMessageVisibilityBatch.`
type ChangeMessageVisibilityBatchResultEntry struct {
	Id *string `json:"Id,omitempty"` // Represents a message whose visibility timeout has been changed successfully.
}

// ChangeMessageVisibilityRequest represents the ChangeMessageVisibilityRequest structure.
type ChangeMessageVisibilityRequest struct {
	QueueUrl          *string `json:"QueueUrl,omitempty"`          // The URL of the Amazon SQS queue whose message's visibility is changed. Queue URLs and names are c...
	ReceiptHandle     *string `json:"ReceiptHandle,omitempty"`     // The receipt handle associated with the message, whose visibility timeout is changed. This paramet...
	VisibilityTimeout *int32  `json:"VisibilityTimeout,omitempty"` // The new value for the message's visibility timeout (in seconds). Values range: `0` to `43200`. Ma...
}

// CreateQueueRequest represents the CreateQueueRequest structure.
type CreateQueueRequest struct {
	Attributes map[string]string `json:"Attributes,omitempty"` // A map of attributes with their corresponding values. The following lists the names, descriptions,...
	QueueName  *string           `json:"QueueName,omitempty"`  // The name of the new queue. The following limits apply to this name: - A queue name can have up to...
	Tags       map[string]string `json:"tags,omitempty"`       // Add cost allocation tags to the specified Amazon SQS queue. For an overview, see Tagging Your Ama...
}

// DeleteMessageBatchRequest represents the DeleteMessageBatchRequest structure.
type DeleteMessageBatchRequest struct {
	Entries  []DeleteMessageBatchRequestEntry `json:"Entries,omitempty"`  // Lists the receipt handles for the messages to be deleted.
	QueueUrl *string                          `json:"QueueUrl,omitempty"` // The URL of the Amazon SQS queue from which messages are deleted. Queue URLs and names are case-se...
}

// DeleteMessageBatchRequestEntry Encloses a receipt handle and an identifier for it.
type DeleteMessageBatchRequestEntry struct {
	Id            *string `json:"Id,omitempty"`            // The identifier for this particular receipt handle. This is used to communicate the result. The `I...
	ReceiptHandle *string `json:"ReceiptHandle,omitempty"` // A receipt handle.
}

// DeleteMessageBatchResultEntry Encloses the `Id` of an entry in ` DeleteMessageBatch.`
type DeleteMessageBatchResultEntry struct {
	Id *string `json:"Id,omitempty"` // Represents a successfully deleted message.
}

// DeleteMessageRequest represents the DeleteMessageRequest structure.
type DeleteMessageRequest struct {
	QueueUrl      *string `json:"QueueUrl,omitempty"`      // The URL of the Amazon SQS queue from which messages are deleted. Queue URLs and names are case-se...
	ReceiptHandle *string `json:"ReceiptHandle,omitempty"` // The receipt handle associated with the message to delete.
}

// DeleteQueueRequest represents the DeleteQueueRequest structure.
type DeleteQueueRequest struct {
	QueueUrl *string `json:"QueueUrl,omitempty"` // The URL of the Amazon SQS queue to delete. Queue URLs and names are case-sensitive.
}

// GetQueueAttributesRequest represents the GetQueueAttributesRequest structure.
type GetQueueAttributesRequest struct {
	AttributeNames []QueueAttributeName `json:"AttributeNames,omitempty"` // A list of attributes for which to retrieve information. The `AttributeNames` parameter is optiona...
	QueueUrl       *string              `json:"QueueUrl,omitempty"`       // The URL of the Amazon SQS queue whose attribute information is retrieved. Queue URLs and names ar...
}

// GetQueueUrlRequest Retrieves the URL of an existing queue based on its name and, optionally, the Amazon Web Services...
type GetQueueUrlRequest struct {
	QueueName              *string `json:"QueueName,omitempty"`              // (Required) The name of the queue for which you want to fetch the URL. The name can be up to 80 ch...
	QueueOwnerAWSAccountId *string `json:"QueueOwnerAWSAccountId,omitempty"` // (Optional) The Amazon Web Services account ID of the account that created the queue. This is only...
}

// ListDeadLetterSourceQueuesRequest represents the ListDeadLetterSourceQueuesRequest structure.
type ListDeadLetterSourceQueuesRequest struct {
	MaxResults *int32  `json:"MaxResults,omitempty"` // Maximum number of results to include in the response. Value range is 1 to 1000. You must set `Max...
	NextToken  *string `json:"NextToken,omitempty"`  // Pagination token to request the next set of results.
	QueueUrl   *string `json:"QueueUrl,omitempty"`   // The URL of a dead-letter queue. Queue URLs and names are case-sensitive.
}

// ListMessageMoveTasksRequest represents the ListMessageMoveTasksRequest structure.
type ListMessageMoveTasksRequest struct {
	MaxResults *int32  `json:"MaxResults,omitempty"` // The maximum number of results to include in the response. The default is 1, which provides the mo...
	SourceArn  *string `json:"SourceArn,omitempty"`  // The ARN of the queue whose message movement tasks are to be listed.
}

// ListMessageMoveTasksResultEntry Contains the details of a message movement task.
type ListMessageMoveTasksResultEntry struct {
	ApproximateNumberOfMessagesMoved  *int64  `json:"ApproximateNumberOfMessagesMoved,omitempty"`  // The approximate number of messages already moved to the destination queue.
	ApproximateNumberOfMessagesToMove *int64  `json:"ApproximateNumberOfMessagesToMove,omitempty"` // The number of messages to be moved from the source queue. This number is obtained at the time of ...
	DestinationArn                    *string `json:"DestinationArn,omitempty"`                    // The ARN of the destination queue if it has been specified in the `StartMessageMoveTask` request. ...
	FailureReason                     *string `json:"FailureReason,omitempty"`                     // The task failure reason (only included if the task status is FAILED).
	MaxNumberOfMessagesPerSecond      *int32  `json:"MaxNumberOfMessagesPerSecond,omitempty"`      // The number of messages to be moved per second (the message movement rate), if it has been specifi...
	SourceArn                         *string `json:"SourceArn,omitempty"`                         // The ARN of the queue that contains the messages to be moved to another queue.
	StartedTimestamp                  *int64  `json:"StartedTimestamp,omitempty"`                  // The timestamp of starting the message movement task.
	Status                            *string `json:"Status,omitempty"`                            // The status of the message movement task. Possible values are: RUNNING, COMPLETED, CANCELLING, CAN...
	TaskHandle                        *string `json:"TaskHandle,omitempty"`                        // An identifier associated with a message movement task. When this field is returned in the respons...
}

// ListQueueTagsRequest represents the ListQueueTagsRequest structure.
type ListQueueTagsRequest struct {
	QueueUrl *string `json:"QueueUrl,omitempty"` // The URL of the queue.
}

// ListQueuesRequest represents the ListQueuesRequest structure.
type ListQueuesRequest struct {
	MaxResults      *int32  `json:"MaxResults,omitempty"`      // Maximum number of results to include in the response. Value range is 1 to 1000. You must set `Max...
	NextToken       *string `json:"NextToken,omitempty"`       // Pagination token to request the next set of results.
	QueueNamePrefix *string `json:"QueueNamePrefix,omitempty"` // A string to use for filtering the list results. Only those queues whose name begins with the spec...
}

// Message An Amazon SQS message.
type Message struct {
	Attributes             map[string]string `json:"Attributes,omitempty"`             // A map of the attributes requested in ` ReceiveMessage ` to their respective values. Supported att...
	Body                   *string           `json:"Body,omitempty"`                   // The message's contents (not URL-encoded).
	MD5OfBody              *string           `json:"MD5OfBody,omitempty"`              // An MD5 digest of the non-URL-encoded message body string.
	MD5OfMessageAttributes *string           `json:"MD5OfMessageAttributes,omitempty"` // An MD5 digest of the non-URL-encoded message attribute string. You can use this attribute to veri...
	MessageAttributes      map[string]string `json:"MessageAttributes,omitempty"`      // Each message attribute consists of a `Name`, `Type`, and `Value`. For more information, see Amazo...
	MessageId              *string           `json:"MessageId,omitempty"`              // A unique identifier for the message. A `MessageId`is considered unique across all Amazon Web Serv...
	ReceiptHandle          *string           `json:"ReceiptHandle,omitempty"`          // An identifier associated with the act of receiving the message. A new receipt handle is returned ...
}

// PurgeQueueRequest represents the PurgeQueueRequest structure.
type PurgeQueueRequest struct {
	QueueUrl *string `json:"QueueUrl,omitempty"` // The URL of the queue from which the `PurgeQueue` action deletes messages. Queue URLs and names ar...
}

// ReceiveMessageRequest Retrieves one or more messages from a specified queue.
type ReceiveMessageRequest struct {
	AttributeNames              []QueueAttributeName         `json:"AttributeNames,omitempty"`              // This parameter has been discontinued but will be supported for backward compatibility. To provide...
	MaxNumberOfMessages         *int32                       `json:"MaxNumberOfMessages,omitempty"`         // The maximum number of messages to return. Amazon SQS never returns more messages than this value ...
	MessageAttributeNames       []string                     `json:"MessageAttributeNames,omitempty"`       // The name of the message attribute, where N is the index. - The name can contain alphanumeric char...
	MessageSystemAttributeNames []MessageSystemAttributeName `json:"MessageSystemAttributeNames,omitempty"` // A list of attributes that need to be returned along with each message. These attributes include: ...
	QueueUrl                    *string                      `json:"QueueUrl,omitempty"`                    // The URL of the Amazon SQS queue from which messages are received. Queue URLs and names are case-s...
	ReceiveRequestAttemptId     *string                      `json:"ReceiveRequestAttemptId,omitempty"`     // This parameter applies only to FIFO (first-in-first-out) queues. The token used for deduplication...
	VisibilityTimeout           *int32                       `json:"VisibilityTimeout,omitempty"`           // The duration (in seconds) that the received messages are hidden from subsequent retrieve requests...
	WaitTimeSeconds             *int32                       `json:"WaitTimeSeconds,omitempty"`             // The duration (in seconds) for which the call waits for a message to arrive in the queue before re...
}

// RemovePermissionRequest represents the RemovePermissionRequest structure.
type RemovePermissionRequest struct {
	Label    *string `json:"Label,omitempty"`    // The identification of the permission to remove. This is the label added using the ` AddPermission...
	QueueUrl *string `json:"QueueUrl,omitempty"` // The URL of the Amazon SQS queue from which permissions are removed. Queue URLs and names are case...
}

// SendMessageBatchRequest represents the SendMessageBatchRequest structure.
type SendMessageBatchRequest struct {
	Entries  []SendMessageBatchRequestEntry `json:"Entries,omitempty"`  // A list of ` SendMessageBatchRequestEntry ` items.
	QueueUrl *string                        `json:"QueueUrl,omitempty"` // The URL of the Amazon SQS queue to which batched messages are sent. Queue URLs and names are case...
}

// SendMessageBatchRequestEntry Contains the details of a single Amazon SQS message along with an `Id`.
type SendMessageBatchRequestEntry struct {
	DelaySeconds            *int32            `json:"DelaySeconds,omitempty"`            // The length of time, in seconds, for which a specific message is delayed. Valid values: 0 to 900. ...
	Id                      *string           `json:"Id,omitempty"`                      // An identifier for a message in this batch used to communicate the result. The `Id`s of a batch re...
	MessageAttributes       map[string]string `json:"MessageAttributes,omitempty"`       // Each message attribute consists of a `Name`, `Type`, and `Value`. For more information, see Amazo...
	MessageBody             *string           `json:"MessageBody,omitempty"`             // The body of the message.
	MessageDeduplicationId  *string           `json:"MessageDeduplicationId,omitempty"`  // This parameter applies only to FIFO (first-in-first-out) queues. The token used for deduplication...
	MessageGroupId          *string           `json:"MessageGroupId,omitempty"`          // `MessageGroupId` is an attribute used in Amazon SQS FIFO (First-In-First-Out) and standard queues...
	MessageSystemAttributes map[string]string `json:"MessageSystemAttributes,omitempty"` // The message system attribute to send Each message system attribute consists of a `Name`, `Type`, ...
}

// SendMessageBatchResultEntry Encloses a `MessageId` for a successfully-enqueued message in a ` SendMessageBatch.`
type SendMessageBatchResultEntry struct {
	Id                           *string `json:"Id,omitempty"`                           // An identifier for the message in this batch.
	MD5OfMessageAttributes       *string `json:"MD5OfMessageAttributes,omitempty"`       // An MD5 digest of the non-URL-encoded message attribute string. You can use this attribute to veri...
	MD5OfMessageBody             *string `json:"MD5OfMessageBody,omitempty"`             // An MD5 digest of the non-URL-encoded message body string. You can use this attribute to verify th...
	MD5OfMessageSystemAttributes *string `json:"MD5OfMessageSystemAttributes,omitempty"` // An MD5 digest of the non-URL-encoded message system attribute string. You can use this attribute ...
	MessageId                    *string `json:"MessageId,omitempty"`                    // An identifier for the message.
	SequenceNumber               *string `json:"SequenceNumber,omitempty"`               // This parameter applies only to FIFO (first-in-first-out) queues. The large, non-consecutive numbe...
}

// SendMessageRequest represents the SendMessageRequest structure.
type SendMessageRequest struct {
	DelaySeconds            *int32            `json:"DelaySeconds,omitempty"`            // The length of time, in seconds, for which to delay a specific message. Valid values: 0 to 900. Ma...
	MessageAttributes       map[string]string `json:"MessageAttributes,omitempty"`       // Each message attribute consists of a `Name`, `Type`, and `Value`. For more information, see Amazo...
	MessageBody             *string           `json:"MessageBody,omitempty"`             // The message to send. The minimum size is one character. The maximum size is 1 MiB or 1,048,576 by...
	MessageDeduplicationId  *string           `json:"MessageDeduplicationId,omitempty"`  // This parameter applies only to FIFO (first-in-first-out) queues. The token used for deduplication...
	MessageGroupId          *string           `json:"MessageGroupId,omitempty"`          // `MessageGroupId` is an attribute used in Amazon SQS FIFO (First-In-First-Out) and standard queues...
	MessageSystemAttributes map[string]string `json:"MessageSystemAttributes,omitempty"` // The message system attribute to send. Each message system attribute consists of a `Name`, `Type`,...
	QueueUrl                *string           `json:"QueueUrl,omitempty"`                // The URL of the Amazon SQS queue to which a message is sent. Queue URLs and names are case-sensitive.
}

// SetQueueAttributesRequest represents the SetQueueAttributesRequest structure.
type SetQueueAttributesRequest struct {
	Attributes map[string]string `json:"Attributes,omitempty"` // A map of attributes to set. The following lists the names, descriptions, and values of the specia...
	QueueUrl   *string           `json:"QueueUrl,omitempty"`   // The URL of the Amazon SQS queue whose attributes are set. Queue URLs and names are case-sensitive.
}

// StartMessageMoveTaskRequest represents the StartMessageMoveTaskRequest structure.
type StartMessageMoveTaskRequest struct {
	DestinationArn               *string `json:"DestinationArn,omitempty"`               // The ARN of the queue that receives the moved messages. You can use this field to specify the dest...
	MaxNumberOfMessagesPerSecond *int32  `json:"MaxNumberOfMessagesPerSecond,omitempty"` // The number of messages to be moved per second (the message movement rate). You can use this field...
	SourceArn                    *string `json:"SourceArn,omitempty"`                    // The ARN of the queue that contains the messages to be moved to another queue. Currently, only ARN...
}

// TagQueueRequest represents the TagQueueRequest structure.
type TagQueueRequest struct {
	QueueUrl *string           `json:"QueueUrl,omitempty"` // The URL of the queue.
	Tags     map[string]string `json:"Tags,omitempty"`     // The list of tags to be added to the specified queue.
}

// UntagQueueRequest represents the UntagQueueRequest structure.
type UntagQueueRequest struct {
	QueueUrl *string  `json:"QueueUrl,omitempty"` // The URL of the queue.
	TagKeys  []string `json:"TagKeys,omitempty"`  // The list of tags to be removed from the specified queue.
}
