// Code generated by CloudMirror from AWS Smithy models. DO NOT EDIT.
// Source: /Users/robbym/.cloudmirror/api-models-aws/models/application-auto-scaling/service/2016-02-06/application-auto-scaling-2016-02-06.json
// Service: applicationautoscaling
// Protocol: json
// Generated: 2025-12-18T03:13:19Z

package applicationautoscaling

import (
	"encoding/json"
	"time"
)

// UnixTimestamp is a time.Time that serializes to/from Unix epoch seconds for JSON.
// AWS JSON protocol expects timestamps as numbers (e.g., 1734574653.902), not RFC3339 strings.
type UnixTimestamp time.Time

// MarshalJSON serializes UnixTimestamp as a Unix epoch float64
func (t UnixTimestamp) MarshalJSON() ([]byte, error) {
	return json.Marshal(float64(time.Time(t).UnixNano()) / 1e9)
}

// UnmarshalJSON deserializes a Unix epoch float64 into UnixTimestamp
func (t *UnixTimestamp) UnmarshalJSON(data []byte) error {
	var f float64
	if err := json.Unmarshal(data, &f); err != nil {
		return err
	}
	sec := int64(f)
	nsec := int64((f - float64(sec)) * 1e9)
	*t = UnixTimestamp(time.Unix(sec, nsec))
	return nil
}

// Enum type aliases

type AdjustmentType string

type MetricAggregationType string

type MetricStatistic string

type MetricType string

type PolicyType string

type PredictiveScalingMaxCapacityBreachBehavior string

type PredictiveScalingMode string

type ScalableDimension string

type ScalingActivityStatusCode string

type ServiceNamespace string

// DeleteScalingPolicyResponse represents the DeleteScalingPolicyResponse structure.
type DeleteScalingPolicyResponse struct{}

// DeleteScheduledActionResponse represents the DeleteScheduledActionResponse structure.
type DeleteScheduledActionResponse struct{}

// DeregisterScalableTargetResponse represents the DeregisterScalableTargetResponse structure.
type DeregisterScalableTargetResponse struct{}

// DescribeScalableTargetsResponse represents the DescribeScalableTargetsResponse structure.
type DescribeScalableTargetsResponse struct {
	NextToken       *string          `json:"NextToken,omitempty"`       // The token required to get the next set of results. This value is `null` if there are no more resu...
	ScalableTargets []ScalableTarget `json:"ScalableTargets,omitempty"` // The scalable targets that match the request parameters.
}

// DescribeScalingActivitiesResponse represents the DescribeScalingActivitiesResponse structure.
type DescribeScalingActivitiesResponse struct {
	NextToken         *string           `json:"NextToken,omitempty"`         // The token required to get the next set of results. This value is `null` if there are no more resu...
	ScalingActivities []ScalingActivity `json:"ScalingActivities,omitempty"` // A list of scaling activity objects.
}

// DescribeScalingPoliciesResponse represents the DescribeScalingPoliciesResponse structure.
type DescribeScalingPoliciesResponse struct {
	NextToken       *string         `json:"NextToken,omitempty"`       // The token required to get the next set of results. This value is `null` if there are no more resu...
	ScalingPolicies []ScalingPolicy `json:"ScalingPolicies,omitempty"` // Information about the scaling policies.
}

// DescribeScheduledActionsResponse represents the DescribeScheduledActionsResponse structure.
type DescribeScheduledActionsResponse struct {
	NextToken        *string           `json:"NextToken,omitempty"`        // The token required to get the next set of results. This value is `null` if there are no more resu...
	ScheduledActions []ScheduledAction `json:"ScheduledActions,omitempty"` // Information about the scheduled actions.
}

// GetPredictiveScalingForecastResponse represents the GetPredictiveScalingForecastResponse structure.
type GetPredictiveScalingForecastResponse struct {
	CapacityForecast *CapacityForecast `json:"CapacityForecast,omitempty"` // The capacity forecast.
	LoadForecast     []LoadForecast    `json:"LoadForecast,omitempty"`     // The load forecast.
	UpdateTime       *time.Time        `json:"UpdateTime,omitempty"`       // The time the forecast was made.
}

// ListTagsForResourceResponse represents the ListTagsForResourceResponse structure.
type ListTagsForResourceResponse struct {
	Tags map[string]string `json:"Tags,omitempty"` // A list of tags. Each tag consists of a tag key and a tag value.
}

// PutScalingPolicyResponse represents the PutScalingPolicyResponse structure.
type PutScalingPolicyResponse struct {
	Alarms    []Alarm `json:"Alarms,omitempty"`    // The CloudWatch alarms created for the target tracking scaling policy.
	PolicyARN *string `json:"PolicyARN,omitempty"` // The Amazon Resource Name (ARN) of the resulting scaling policy.
}

// PutScheduledActionResponse represents the PutScheduledActionResponse structure.
type PutScheduledActionResponse struct{}

// RegisterScalableTargetResponse represents the RegisterScalableTargetResponse structure.
type RegisterScalableTargetResponse struct {
	ScalableTargetARN *string `json:"ScalableTargetARN,omitempty"` // The ARN of the scalable target.
}

// TagResourceResponse represents the TagResourceResponse structure.
type TagResourceResponse struct{}

// UntagResourceResponse represents the UntagResourceResponse structure.
type UntagResourceResponse struct{}

// Alarm Represents a CloudWatch alarm associated with a scaling policy.
type Alarm struct {
	AlarmARN  *string `json:"AlarmARN,omitempty"`  // The Amazon Resource Name (ARN) of the alarm.
	AlarmName *string `json:"AlarmName,omitempty"` // The name of the alarm.
}

// CapacityForecast A `GetPredictiveScalingForecast` call returns the capacity forecast for a predictive scaling poli...
type CapacityForecast struct {
	Timestamps []time.Time `json:"Timestamps,omitempty"` // The timestamps for the data points, in UTC format.
	Values     []float64   `json:"Values,omitempty"`     // The values of the data points.
}

// CustomizedMetricSpecification Represents a CloudWatch metric of your choosing for a target tracking scaling policy to use with ...
type CustomizedMetricSpecification struct {
	Dimensions []MetricDimension               `json:"Dimensions,omitempty"` // The dimensions of the metric. Conditional: If you published your metric with dimensions, you must...
	MetricName *string                         `json:"MetricName,omitempty"` // The name of the metric. To get the exact metric name, namespace, and dimensions, inspect the Metr...
	Metrics    []TargetTrackingMetricDataQuery `json:"Metrics,omitempty"`    // The metrics to include in the target tracking scaling policy, as a metric data query. This can in...
	Namespace  *string                         `json:"Namespace,omitempty"`  // The namespace of the metric.
	Statistic  MetricStatistic                 `json:"Statistic,omitempty"`  // The statistic of the metric.
	Unit       *string                         `json:"Unit,omitempty"`       // The unit of the metric. For a complete list of the units that CloudWatch supports, see the Metric...
}

// DeleteScalingPolicyRequest represents the DeleteScalingPolicyRequest structure.
type DeleteScalingPolicyRequest struct {
	PolicyName        *string           `json:"PolicyName,omitempty"`        // The name of the scaling policy.
	ResourceId        *string           `json:"ResourceId,omitempty"`        // The identifier of the resource associated with the scalable target. This string consists of the r...
	ScalableDimension ScalableDimension `json:"ScalableDimension,omitempty"` // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ServiceNamespace  ServiceNamespace  `json:"ServiceNamespace,omitempty"`  // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
}

// DeleteScheduledActionRequest represents the DeleteScheduledActionRequest structure.
type DeleteScheduledActionRequest struct {
	ResourceId          *string           `json:"ResourceId,omitempty"`          // The identifier of the resource associated with the scheduled action. This string consists of the ...
	ScalableDimension   ScalableDimension `json:"ScalableDimension,omitempty"`   // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ScheduledActionName *string           `json:"ScheduledActionName,omitempty"` // The name of the scheduled action.
	ServiceNamespace    ServiceNamespace  `json:"ServiceNamespace,omitempty"`    // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
}

// DeregisterScalableTargetRequest represents the DeregisterScalableTargetRequest structure.
type DeregisterScalableTargetRequest struct {
	ResourceId        *string           `json:"ResourceId,omitempty"`        // The identifier of the resource associated with the scalable target. This string consists of the r...
	ScalableDimension ScalableDimension `json:"ScalableDimension,omitempty"` // The scalable dimension associated with the scalable target. This string consists of the service n...
	ServiceNamespace  ServiceNamespace  `json:"ServiceNamespace,omitempty"`  // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
}

// DescribeScalableTargetsRequest represents the DescribeScalableTargetsRequest structure.
type DescribeScalableTargetsRequest struct {
	MaxResults        *int32            `json:"MaxResults,omitempty"`        // The maximum number of scalable targets. This value can be between 1 and 50. The default value is ...
	NextToken         *string           `json:"NextToken,omitempty"`         // The token for the next set of results.
	ResourceIds       []string          `json:"ResourceIds,omitempty"`       // The identifier of the resource associated with the scalable target. This string consists of the r...
	ScalableDimension ScalableDimension `json:"ScalableDimension,omitempty"` // The scalable dimension associated with the scalable target. This string consists of the service n...
	ServiceNamespace  ServiceNamespace  `json:"ServiceNamespace,omitempty"`  // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
}

// DescribeScalingActivitiesRequest represents the DescribeScalingActivitiesRequest structure.
type DescribeScalingActivitiesRequest struct {
	IncludeNotScaledActivities *bool             `json:"IncludeNotScaledActivities,omitempty"` // Specifies whether to include activities that aren't scaled (not scaled activities) in the respons...
	MaxResults                 *int32            `json:"MaxResults,omitempty"`                 // The maximum number of scalable targets. This value can be between 1 and 50. The default value is ...
	NextToken                  *string           `json:"NextToken,omitempty"`                  // The token for the next set of results.
	ResourceId                 *string           `json:"ResourceId,omitempty"`                 // The identifier of the resource associated with the scaling activity. This string consists of the ...
	ScalableDimension          ScalableDimension `json:"ScalableDimension,omitempty"`          // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ServiceNamespace           ServiceNamespace  `json:"ServiceNamespace,omitempty"`           // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
}

// DescribeScalingPoliciesRequest represents the DescribeScalingPoliciesRequest structure.
type DescribeScalingPoliciesRequest struct {
	MaxResults        *int32            `json:"MaxResults,omitempty"`        // The maximum number of scalable targets. This value can be between 1 and 10. The default value is ...
	NextToken         *string           `json:"NextToken,omitempty"`         // The token for the next set of results.
	PolicyNames       []string          `json:"PolicyNames,omitempty"`       // The names of the scaling policies to describe.
	ResourceId        *string           `json:"ResourceId,omitempty"`        // The identifier of the resource associated with the scaling policy. This string consists of the re...
	ScalableDimension ScalableDimension `json:"ScalableDimension,omitempty"` // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ServiceNamespace  ServiceNamespace  `json:"ServiceNamespace,omitempty"`  // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
}

// DescribeScheduledActionsRequest represents the DescribeScheduledActionsRequest structure.
type DescribeScheduledActionsRequest struct {
	MaxResults           *int32            `json:"MaxResults,omitempty"`           // The maximum number of scheduled action results. This value can be between 1 and 50. The default v...
	NextToken            *string           `json:"NextToken,omitempty"`            // The token for the next set of results.
	ResourceId           *string           `json:"ResourceId,omitempty"`           // The identifier of the resource associated with the scheduled action. This string consists of the ...
	ScalableDimension    ScalableDimension `json:"ScalableDimension,omitempty"`    // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ScheduledActionNames []string          `json:"ScheduledActionNames,omitempty"` // The names of the scheduled actions to describe.
	ServiceNamespace     ServiceNamespace  `json:"ServiceNamespace,omitempty"`     // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
}

// GetPredictiveScalingForecastRequest represents the GetPredictiveScalingForecastRequest structure.
type GetPredictiveScalingForecastRequest struct {
	EndTime           *time.Time        `json:"EndTime,omitempty"`           // The exclusive end time of the time range for the forecast data to get. The maximum time duration ...
	PolicyName        *string           `json:"PolicyName,omitempty"`        // The name of the policy.
	ResourceId        *string           `json:"ResourceId,omitempty"`        // The identifier of the resource.
	ScalableDimension ScalableDimension `json:"ScalableDimension,omitempty"` // The scalable dimension.
	ServiceNamespace  ServiceNamespace  `json:"ServiceNamespace,omitempty"`  // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
	StartTime         *time.Time        `json:"StartTime,omitempty"`         // The inclusive start time of the time range for the forecast data to get. At most, the date and ti...
}

// ListTagsForResourceRequest represents the ListTagsForResourceRequest structure.
type ListTagsForResourceRequest struct {
	ResourceARN *string `json:"ResourceARN,omitempty"` // Specify the ARN of the scalable target. For example: `arn:aws:application-autoscaling:us-east-1:1...
}

// LoadForecast A `GetPredictiveScalingForecast` call returns the load forecast for a predictive scaling policy. ...
type LoadForecast struct {
	MetricSpecification *PredictiveScalingMetricSpecification `json:"MetricSpecification,omitempty"` // The metric specification for the load forecast.
	Timestamps          []time.Time                           `json:"Timestamps,omitempty"`          // The timestamps for the data points, in UTC format.
	Values              []float64                             `json:"Values,omitempty"`              // The values of the data points.
}

// MetricDimension Describes the dimension names and values associated with a metric.
type MetricDimension struct {
	Name  *string `json:"Name,omitempty"`  // The name of the dimension.
	Value *string `json:"Value,omitempty"` // The value of the dimension.
}

// NotScaledReason Describes the reason for an activity that isn't scaled (not scaled activity), in machine-readable...
type NotScaledReason struct {
	Code            *string `json:"Code,omitempty"`            // A code that represents the reason for not scaling. Valid values: - AutoScalingAnticipatedFlapping...
	CurrentCapacity *int32  `json:"CurrentCapacity,omitempty"` // The current capacity.
	MaxCapacity     *int32  `json:"MaxCapacity,omitempty"`     // The maximum capacity.
	MinCapacity     *int32  `json:"MinCapacity,omitempty"`     // The minimum capacity.
}

// PredefinedMetricSpecification Represents a predefined metric for a target tracking scaling policy to use with Application Auto ...
type PredefinedMetricSpecification struct {
	PredefinedMetricType MetricType `json:"PredefinedMetricType,omitempty"` // The metric type. The `ALBRequestCountPerTarget` metric type applies only to Spot Fleets and ECS s...
	ResourceLabel        *string    `json:"ResourceLabel,omitempty"`        // Identifies the resource associated with the metric type. You can't specify a resource label unles...
}

// PredictiveScalingCustomizedMetricSpecification Represents a CloudWatch metric of your choosing for a predictive scaling policy.
type PredictiveScalingCustomizedMetricSpecification struct {
	MetricDataQueries []PredictiveScalingMetricDataQuery `json:"MetricDataQueries,omitempty"` // One or more metric data queries to provide data points for a metric specification.
}

// PredictiveScalingMetric Describes the scaling metric.
type PredictiveScalingMetric struct {
	Dimensions []PredictiveScalingMetricDimension `json:"Dimensions,omitempty"` // Describes the dimensions of the metric.
	MetricName *string                            `json:"MetricName,omitempty"` // The name of the metric.
	Namespace  *string                            `json:"Namespace,omitempty"`  // The namespace of the metric.
}

// PredictiveScalingMetricDataQuery The metric data to return. Also defines whether this call is returning data for one metric only, ...
type PredictiveScalingMetricDataQuery struct {
	Expression *string                      `json:"Expression,omitempty"` // The math expression to perform on the returned data, if this object is performing a math expressi...
	Id         *string                      `json:"Id,omitempty"`         // A short name that identifies the object's results in the response. This name must be unique among...
	Label      *string                      `json:"Label,omitempty"`      // A human-readable label for this metric or expression. This is especially useful if this is a math...
	MetricStat *PredictiveScalingMetricStat `json:"MetricStat,omitempty"` // Information about the metric data to return. Conditional: Within each `MetricDataQuery` object, y...
	ReturnData *bool                        `json:"ReturnData,omitempty"` // Indicates whether to return the timestamps and raw data values of this metric. If you use any mat...
}

// PredictiveScalingMetricDimension Describes the dimension of a metric.
type PredictiveScalingMetricDimension struct {
	Name  *string `json:"Name,omitempty"`  // The name of the dimension.
	Value *string `json:"Value,omitempty"` // The value of the dimension.
}

// PredictiveScalingMetricSpecification This structure specifies the metrics and target utilization settings for a predictive scaling pol...
type PredictiveScalingMetricSpecification struct {
	CustomizedCapacityMetricSpecification *PredictiveScalingCustomizedMetricSpecification        `json:"CustomizedCapacityMetricSpecification,omitempty"` // The customized capacity metric specification.
	CustomizedLoadMetricSpecification     *PredictiveScalingCustomizedMetricSpecification        `json:"CustomizedLoadMetricSpecification,omitempty"`     // The customized load metric specification.
	CustomizedScalingMetricSpecification  *PredictiveScalingCustomizedMetricSpecification        `json:"CustomizedScalingMetricSpecification,omitempty"`  // The customized scaling metric specification.
	PredefinedLoadMetricSpecification     *PredictiveScalingPredefinedLoadMetricSpecification    `json:"PredefinedLoadMetricSpecification,omitempty"`     // The predefined load metric specification.
	PredefinedMetricPairSpecification     *PredictiveScalingPredefinedMetricPairSpecification    `json:"PredefinedMetricPairSpecification,omitempty"`     // The predefined metric pair specification that determines the appropriate scaling metric and load ...
	PredefinedScalingMetricSpecification  *PredictiveScalingPredefinedScalingMetricSpecification `json:"PredefinedScalingMetricSpecification,omitempty"`  // The predefined scaling metric specification.
	TargetValue                           *float64                                               `json:"TargetValue,omitempty"`                           // Specifies the target utilization.
}

// PredictiveScalingMetricStat This structure defines the CloudWatch metric to return, along with the statistic and unit.
type PredictiveScalingMetricStat struct {
	Metric *PredictiveScalingMetric `json:"Metric,omitempty"` // The CloudWatch metric to return, including the metric name, namespace, and dimensions. To get the...
	Stat   *string                  `json:"Stat,omitempty"`   // The statistic to return. It can include any CloudWatch statistic or extended statistic. For a lis...
	Unit   *string                  `json:"Unit,omitempty"`   // The unit to use for the returned data points. For a complete list of the units that CloudWatch su...
}

// PredictiveScalingPolicyConfiguration Represents a predictive scaling policy configuration. Predictive scaling is supported on Amazon E...
type PredictiveScalingPolicyConfiguration struct {
	MaxCapacityBreachBehavior PredictiveScalingMaxCapacityBreachBehavior `json:"MaxCapacityBreachBehavior,omitempty"` // Defines the behavior that should be applied if the forecast capacity approaches or exceeds the ma...
	MaxCapacityBuffer         *int32                                     `json:"MaxCapacityBuffer,omitempty"`         // The size of the capacity buffer to use when the forecast capacity is close to or exceeds the maxi...
	MetricSpecifications      []PredictiveScalingMetricSpecification     `json:"MetricSpecifications,omitempty"`      // This structure includes the metrics and target utilization to use for predictive scaling. This is...
	Mode                      PredictiveScalingMode                      `json:"Mode,omitempty"`                      // The predictive scaling mode. Defaults to `ForecastOnly` if not specified.
	SchedulingBufferTime      *int32                                     `json:"SchedulingBufferTime,omitempty"`      // The amount of time, in seconds, that the start time can be advanced. The value must be less than ...
}

// PredictiveScalingPredefinedLoadMetricSpecification Describes a load metric for a predictive scaling policy. When returned in the output of `Describe...
type PredictiveScalingPredefinedLoadMetricSpecification struct {
	PredefinedMetricType *string `json:"PredefinedMetricType,omitempty"` // The metric type.
	ResourceLabel        *string `json:"ResourceLabel,omitempty"`        // A label that uniquely identifies a target group.
}

// PredictiveScalingPredefinedMetricPairSpecification Represents a metric pair for a predictive scaling policy. The following predefined metrics are av...
type PredictiveScalingPredefinedMetricPairSpecification struct {
	PredefinedMetricType *string `json:"PredefinedMetricType,omitempty"` // Indicates which metrics to use. There are two different types of metrics for each metric type: on...
	ResourceLabel        *string `json:"ResourceLabel,omitempty"`        // A label that uniquely identifies a specific target group from which to determine the total and av...
}

// PredictiveScalingPredefinedScalingMetricSpecification Describes a scaling metric for a predictive scaling policy. When returned in the output of `Descr...
type PredictiveScalingPredefinedScalingMetricSpecification struct {
	PredefinedMetricType *string `json:"PredefinedMetricType,omitempty"` // The metric type.
	ResourceLabel        *string `json:"ResourceLabel,omitempty"`        // A label that uniquely identifies a specific target group from which to determine the average requ...
}

// PutScalingPolicyRequest represents the PutScalingPolicyRequest structure.
type PutScalingPolicyRequest struct {
	PolicyName                               *string                                   `json:"PolicyName,omitempty"`                               // The name of the scaling policy. You cannot change the name of a scaling policy, but you can delet...
	PolicyType                               PolicyType                                `json:"PolicyType,omitempty"`                               // The scaling policy type. This parameter is required if you are creating a scaling policy. The fol...
	PredictiveScalingPolicyConfiguration     *PredictiveScalingPolicyConfiguration     `json:"PredictiveScalingPolicyConfiguration,omitempty"`     // The configuration of the predictive scaling policy.
	ResourceId                               *string                                   `json:"ResourceId,omitempty"`                               // The identifier of the resource associated with the scaling policy. This string consists of the re...
	ScalableDimension                        ScalableDimension                         `json:"ScalableDimension,omitempty"`                        // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ServiceNamespace                         ServiceNamespace                          `json:"ServiceNamespace,omitempty"`                         // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
	StepScalingPolicyConfiguration           *StepScalingPolicyConfiguration           `json:"StepScalingPolicyConfiguration,omitempty"`           // A step scaling policy. This parameter is required if you are creating a policy and the policy typ...
	TargetTrackingScalingPolicyConfiguration *TargetTrackingScalingPolicyConfiguration `json:"TargetTrackingScalingPolicyConfiguration,omitempty"` // A target tracking scaling policy. Includes support for predefined or customized metrics. This par...
}

// PutScheduledActionRequest represents the PutScheduledActionRequest structure.
type PutScheduledActionRequest struct {
	EndTime              *time.Time            `json:"EndTime,omitempty"`              // The date and time for the recurring schedule to end, in UTC.
	ResourceId           *string               `json:"ResourceId,omitempty"`           // The identifier of the resource associated with the scheduled action. This string consists of the ...
	ScalableDimension    ScalableDimension     `json:"ScalableDimension,omitempty"`    // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ScalableTargetAction *ScalableTargetAction `json:"ScalableTargetAction,omitempty"` // The new minimum and maximum capacity. You can set both values or just one. At the scheduled time,...
	Schedule             *string               `json:"Schedule,omitempty"`             // The schedule for this action. The following formats are supported: - At expressions - "`at(yyyy-m...
	ScheduledActionName  *string               `json:"ScheduledActionName,omitempty"`  // The name of the scheduled action. This name must be unique among all other scheduled actions on t...
	ServiceNamespace     ServiceNamespace      `json:"ServiceNamespace,omitempty"`     // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
	StartTime            *time.Time            `json:"StartTime,omitempty"`            // The date and time for this scheduled action to start, in UTC.
	Timezone             *string               `json:"Timezone,omitempty"`             // Specifies the time zone used when setting a scheduled action by using an at or cron expression. I...
}

// RegisterScalableTargetRequest represents the RegisterScalableTargetRequest structure.
type RegisterScalableTargetRequest struct {
	MaxCapacity       *int32            `json:"MaxCapacity,omitempty"`       // The maximum value that you plan to scale out to. When a scaling policy is in effect, Application ...
	MinCapacity       *int32            `json:"MinCapacity,omitempty"`       // The minimum value that you plan to scale in to. When a scaling policy is in effect, Application A...
	ResourceId        *string           `json:"ResourceId,omitempty"`        // The identifier of the resource that is associated with the scalable target. This string consists ...
	RoleARN           *string           `json:"RoleARN,omitempty"`           // This parameter is required for services that do not support service-linked roles (such as Amazon ...
	ScalableDimension ScalableDimension `json:"ScalableDimension,omitempty"` // The scalable dimension associated with the scalable target. This string consists of the service n...
	ServiceNamespace  ServiceNamespace  `json:"ServiceNamespace,omitempty"`  // The namespace of the Amazon Web Services service that provides the resource. For a resource provi...
	SuspendedState    *SuspendedState   `json:"SuspendedState,omitempty"`    // An embedded object that contains attributes and attribute values that are used to suspend and res...
	Tags              map[string]string `json:"Tags,omitempty"`              // Assigns one or more tags to the scalable target. Use this parameter to tag the scalable target wh...
}

// ScalableTarget Represents a scalable target.
type ScalableTarget struct {
	CreationTime      *UnixTimestamp    `json:"CreationTime,omitempty"`      // The Unix timestamp for when the scalable target was created.
	MaxCapacity       *int32            `json:"MaxCapacity,omitempty"`       // The maximum value to scale to in response to a scale-out activity.
	MinCapacity       *int32            `json:"MinCapacity,omitempty"`       // The minimum value to scale to in response to a scale-in activity.
	PredictedCapacity *int32            `json:"PredictedCapacity,omitempty"` // The predicted capacity of the scalable target.
	ResourceId        *string           `json:"ResourceId,omitempty"`        // The identifier of the resource associated with the scalable target. This string consists of the r...
	RoleARN           *string           `json:"RoleARN,omitempty"`           // The ARN of an IAM role that allows Application Auto Scaling to modify the scalable target on your...
	ScalableDimension ScalableDimension `json:"ScalableDimension,omitempty"` // The scalable dimension associated with the scalable target. This string consists of the service n...
	ScalableTargetARN *string           `json:"ScalableTargetARN,omitempty"` // The ARN of the scalable target.
	ServiceNamespace  ServiceNamespace  `json:"ServiceNamespace,omitempty"`  // The namespace of the Amazon Web Services service that provides the resource, or a `custom-resource`.
	SuspendedState    *SuspendedState   `json:"SuspendedState,omitempty"`    // Specifies whether the scaling activities for a scalable target are in a suspended state.
}

// ScalableTargetAction Represents the minimum and maximum capacity for a scheduled action.
type ScalableTargetAction struct {
	MaxCapacity *int32 `json:"MaxCapacity,omitempty"` // The maximum capacity. Although you can specify a large maximum capacity, note that service quotas...
	MinCapacity *int32 `json:"MinCapacity,omitempty"` // The minimum capacity. When the scheduled action runs, the resource will have at least this much c...
}

// ScalingActivity Represents a scaling activity.
type ScalingActivity struct {
	ActivityId        *string                   `json:"ActivityId,omitempty"`        // The unique identifier of the scaling activity.
	Cause             *string                   `json:"Cause,omitempty"`             // A simple description of what caused the scaling activity to happen.
	Description       *string                   `json:"Description,omitempty"`       // A simple description of what action the scaling activity intends to accomplish.
	Details           *string                   `json:"Details,omitempty"`           // The details about the scaling activity.
	EndTime           *UnixTimestamp            `json:"EndTime,omitempty"`           // The Unix timestamp for when the scaling activity ended.
	NotScaledReasons  []NotScaledReason         `json:"NotScaledReasons,omitempty"`  // Machine-readable data that describes the reason for a not scaled activity. Only available when De...
	ResourceId        *string                   `json:"ResourceId,omitempty"`        // The identifier of the resource associated with the scaling activity. This string consists of the ...
	ScalableDimension ScalableDimension         `json:"ScalableDimension,omitempty"` // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ServiceNamespace  ServiceNamespace          `json:"ServiceNamespace,omitempty"`  // The namespace of the Amazon Web Services service that provides the resource, or a `custom-resource`.
	StartTime         *UnixTimestamp            `json:"StartTime,omitempty"`         // The Unix timestamp for when the scaling activity began.
	StatusCode        ScalingActivityStatusCode `json:"StatusCode,omitempty"`        // Indicates the status of the scaling activity.
	StatusMessage     *string                   `json:"StatusMessage,omitempty"`     // A simple message about the current status of the scaling activity.
}

// ScalingPolicy Represents a scaling policy to use with Application Auto Scaling. For more information about conf...
type ScalingPolicy struct {
	Alarms                                   []Alarm                                   `json:"Alarms,omitempty"`                                   // The CloudWatch alarms associated with the scaling policy.
	CreationTime                             *UnixTimestamp                            `json:"CreationTime,omitempty"`                             // The Unix timestamp for when the scaling policy was created.
	PolicyARN                                *string                                   `json:"PolicyARN,omitempty"`                                // The Amazon Resource Name (ARN) of the scaling policy.
	PolicyName                               *string                                   `json:"PolicyName,omitempty"`                               // The name of the scaling policy.
	PolicyType                               PolicyType                                `json:"PolicyType,omitempty"`                               // The scaling policy type. The following policy types are supported: `TargetTrackingScaling`—Not ...
	PredictiveScalingPolicyConfiguration     *PredictiveScalingPolicyConfiguration     `json:"PredictiveScalingPolicyConfiguration,omitempty"`     // The predictive scaling policy configuration.
	ResourceId                               *string                                   `json:"ResourceId,omitempty"`                               // The identifier of the resource associated with the scaling policy. This string consists of the re...
	ScalableDimension                        ScalableDimension                         `json:"ScalableDimension,omitempty"`                        // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ServiceNamespace                         ServiceNamespace                          `json:"ServiceNamespace,omitempty"`                         // The namespace of the Amazon Web Services service that provides the resource, or a `custom-resource`.
	StepScalingPolicyConfiguration           *StepScalingPolicyConfiguration           `json:"StepScalingPolicyConfiguration,omitempty"`           // A step scaling policy.
	TargetTrackingScalingPolicyConfiguration *TargetTrackingScalingPolicyConfiguration `json:"TargetTrackingScalingPolicyConfiguration,omitempty"` // A target tracking scaling policy.
}

// ScheduledAction Represents a scheduled action.
type ScheduledAction struct {
	CreationTime         *UnixTimestamp        `json:"CreationTime,omitempty"`         // The date and time that the scheduled action was created.
	EndTime              *UnixTimestamp        `json:"EndTime,omitempty"`              // The date and time that the action is scheduled to end, in UTC.
	ResourceId           *string               `json:"ResourceId,omitempty"`           // The identifier of the resource associated with the scaling policy. This string consists of the re...
	ScalableDimension    ScalableDimension     `json:"ScalableDimension,omitempty"`    // The scalable dimension. This string consists of the service namespace, resource type, and scaling...
	ScalableTargetAction *ScalableTargetAction `json:"ScalableTargetAction,omitempty"` // The new minimum and maximum capacity. You can set both values or just one. At the scheduled time,...
	Schedule             *string               `json:"Schedule,omitempty"`             // The schedule for this action. The following formats are supported: - At expressions - "`at(yyyy-m...
	ScheduledActionARN   *string               `json:"ScheduledActionARN,omitempty"`   // The Amazon Resource Name (ARN) of the scheduled action.
	ScheduledActionName  *string               `json:"ScheduledActionName,omitempty"`  // The name of the scheduled action.
	ServiceNamespace     ServiceNamespace      `json:"ServiceNamespace,omitempty"`     // The namespace of the Amazon Web Services service that provides the resource, or a `custom-resource`.
	StartTime            *UnixTimestamp        `json:"StartTime,omitempty"`            // The date and time that the action is scheduled to begin, in UTC.
	Timezone             *string               `json:"Timezone,omitempty"`             // The time zone used when referring to the date and time of a scheduled action, when the scheduled ...
}

// StepAdjustment Represents a step adjustment for a StepScalingPolicyConfiguration. Describes an adjustment based ...
type StepAdjustment struct {
	MetricIntervalLowerBound *float64 `json:"MetricIntervalLowerBound,omitempty"` // The lower bound for the difference between the alarm threshold and the CloudWatch metric. If the ...
	MetricIntervalUpperBound *float64 `json:"MetricIntervalUpperBound,omitempty"` // The upper bound for the difference between the alarm threshold and the CloudWatch metric. If the ...
	ScalingAdjustment        *int32   `json:"ScalingAdjustment,omitempty"`        // The amount by which to scale, based on the specified adjustment type. A positive value adds to th...
}

// StepScalingPolicyConfiguration Represents a step scaling policy configuration to use with Application Auto Scaling. For more inf...
type StepScalingPolicyConfiguration struct {
	AdjustmentType         AdjustmentType        `json:"AdjustmentType,omitempty"`         // Specifies how the `ScalingAdjustment` value in a StepAdjustment is interpreted (for example, an a...
	Cooldown               *int32                `json:"Cooldown,omitempty"`               // The amount of time, in seconds, to wait for a previous scaling activity to take effect. If not sp...
	MetricAggregationType  MetricAggregationType `json:"MetricAggregationType,omitempty"`  // The aggregation type for the CloudWatch metrics. Valid values are `Minimum`, `Maximum`, and `Aver...
	MinAdjustmentMagnitude *int32                `json:"MinAdjustmentMagnitude,omitempty"` // The minimum value to scale by when the adjustment type is `PercentChangeInCapacity`. For example,...
	StepAdjustments        []StepAdjustment      `json:"StepAdjustments,omitempty"`        // A set of adjustments that enable you to scale based on the size of the alarm breach. At least one...
}

// SuspendedState Specifies whether the scaling activities for a scalable target are in a suspended state.
type SuspendedState struct {
	DynamicScalingInSuspended  *bool `json:"DynamicScalingInSuspended,omitempty"`  // Whether scale in by a target tracking scaling policy or a step scaling policy is suspended. Set t...
	DynamicScalingOutSuspended *bool `json:"DynamicScalingOutSuspended,omitempty"` // Whether scale out by a target tracking scaling policy or a step scaling policy is suspended. Set ...
	ScheduledScalingSuspended  *bool `json:"ScheduledScalingSuspended,omitempty"`  // Whether scheduled scaling is suspended. Set the value to `true` if you don't want Application Aut...
}

// TagResourceRequest represents the TagResourceRequest structure.
type TagResourceRequest struct {
	ResourceARN *string           `json:"ResourceARN,omitempty"` // Identifies the Application Auto Scaling scalable target that you want to apply tags to. For examp...
	Tags        map[string]string `json:"Tags,omitempty"`        // The tags assigned to the resource. A tag is a label that you assign to an Amazon Web Services res...
}

// TargetTrackingMetric Represents a specific metric. Metric is a property of the TargetTrackingMetricStat object.
type TargetTrackingMetric struct {
	Dimensions []TargetTrackingMetricDimension `json:"Dimensions,omitempty"` // The dimensions for the metric. For the list of available dimensions, see the Amazon Web Services ...
	MetricName *string                         `json:"MetricName,omitempty"` // The name of the metric.
	Namespace  *string                         `json:"Namespace,omitempty"`  // The namespace of the metric. For more information, see the table in Amazon Web Services services ...
}

// TargetTrackingMetricDataQuery The metric data to return. Also defines whether this call is returning data for one metric only, ...
type TargetTrackingMetricDataQuery struct {
	Expression *string                   `json:"Expression,omitempty"` // The math expression to perform on the returned data, if this object is performing a math expressi...
	Id         *string                   `json:"Id,omitempty"`         // A short name that identifies the object's results in the response. This name must be unique among...
	Label      *string                   `json:"Label,omitempty"`      // A human-readable label for this metric or expression. This is especially useful if this is a math...
	MetricStat *TargetTrackingMetricStat `json:"MetricStat,omitempty"` // Information about the metric data to return. Conditional: Within each `MetricDataQuery` object, y...
	ReturnData *bool                     `json:"ReturnData,omitempty"` // Indicates whether to return the timestamps and raw data values of this metric. If you use any mat...
}

// TargetTrackingMetricDimension Describes the dimension of a metric.
type TargetTrackingMetricDimension struct {
	Name  *string `json:"Name,omitempty"`  // The name of the dimension.
	Value *string `json:"Value,omitempty"` // The value of the dimension.
}

// TargetTrackingMetricStat This structure defines the CloudWatch metric to return, along with the statistic and unit. For mo...
type TargetTrackingMetricStat struct {
	Metric *TargetTrackingMetric `json:"Metric,omitempty"` // The CloudWatch metric to return, including the metric name, namespace, and dimensions. To get the...
	Stat   *string               `json:"Stat,omitempty"`   // The statistic to return. It can include any CloudWatch statistic or extended statistic. For a lis...
	Unit   *string               `json:"Unit,omitempty"`   // The unit to use for the returned data points. For a complete list of the units that CloudWatch su...
}

// TargetTrackingScalingPolicyConfiguration Represents a target tracking scaling policy configuration to use with Application Auto Scaling. F...
type TargetTrackingScalingPolicyConfiguration struct {
	CustomizedMetricSpecification *CustomizedMetricSpecification `json:"CustomizedMetricSpecification,omitempty"` // A customized metric. You can specify either a predefined metric or a customized metric.
	DisableScaleIn                *bool                          `json:"DisableScaleIn,omitempty"`                // Indicates whether scale in by the target tracking scaling policy is disabled. If the value is `tr...
	PredefinedMetricSpecification *PredefinedMetricSpecification `json:"PredefinedMetricSpecification,omitempty"` // A predefined metric. You can specify either a predefined metric or a customized metric.
	ScaleInCooldown               *int32                         `json:"ScaleInCooldown,omitempty"`               // The amount of time, in seconds, after a scale-in activity completes before another scale-in activ...
	ScaleOutCooldown              *int32                         `json:"ScaleOutCooldown,omitempty"`              // The amount of time, in seconds, to wait for a previous scale-out activity to take effect. For mor...
	TargetValue                   *float64                       `json:"TargetValue,omitempty"`                   // The target value for the metric. Although this property accepts numbers of type Double, it won't ...
}

// UntagResourceRequest represents the UntagResourceRequest structure.
type UntagResourceRequest struct {
	ResourceARN *string  `json:"ResourceARN,omitempty"` // Identifies the Application Auto Scaling scalable target from which to remove tags. For example: `...
	TagKeys     []string `json:"TagKeys,omitempty"`     // One or more tag keys. Specify only the tag keys, not the tag values.
}
