// Code generated by CloudMirror from AWS Smithy models. DO NOT EDIT.
// Source: /Users/robbym/.cloudmirror/api-models-aws/models/lambda/service/2015-03-31/lambda-2015-03-31.json
// Service: lambda
// Protocol: rest-json
// Generated: 2025-12-22T03:29:28Z

package lambda

import (
	"encoding/json"
	"time"
)

// UnixTimestamp is a time.Time that serializes to/from Unix epoch seconds for JSON.
// AWS JSON protocol expects timestamps as numbers (e.g., 1734574653.902), not RFC3339 strings.
type UnixTimestamp time.Time

// MarshalJSON serializes UnixTimestamp as a Unix epoch float64
func (t UnixTimestamp) MarshalJSON() ([]byte, error) {
	return json.Marshal(float64(time.Time(t).UnixNano()) / 1e9)
}

// UnmarshalJSON deserializes a Unix epoch float64 into UnixTimestamp
func (t *UnixTimestamp) UnmarshalJSON(data []byte) error {
	var f float64
	if err := json.Unmarshal(data, &f); err != nil {
		return err
	}
	sec := int64(f)
	nsec := int64((f - float64(sec)) * 1e9)
	*t = UnixTimestamp(time.Unix(sec, nsec))
	return nil
}

// Enum type aliases

type ApplicationLogLevel string

type Architecture string

type CapacityProviderPredefinedMetricType string

type CapacityProviderScalingMode string

type CapacityProviderState string

type CodeSigningPolicy string

type EventSourceMappingMetric string

type EventSourcePosition string

type EventType string

type ExecutionStatus string

type FullDocument string

type FunctionResponseType string

type FunctionUrlAuthType string

type InvokeMode string

type KafkaSchemaRegistryAuthType string

type KafkaSchemaValidationAttribute string

type LastUpdateStatus string

type LastUpdateStatusReasonCode string

type LogFormat string

type OperationStatus string

type OperationType string

type PackageType string

type ProvisionedConcurrencyStatusEnum string

type RecursiveLoop string

type Runtime string

type SchemaRegistryEventRecordFormat string

type SnapStartApplyOn string

type SnapStartOptimizationStatus string

type SourceAccessType string

type State string

type StateReasonCode string

type SystemLogLevel string

type TenantIsolationMode string

type TracingMode string

type UpdateRuntimeOn string

// AddLayerVersionPermissionResponse represents the AddLayerVersionPermissionResponse structure.
type AddLayerVersionPermissionResponse struct {
	RevisionId *string `json:"RevisionId,omitempty"` // A unique identifier for the current revision of the policy.
	Statement  *string `json:"Statement,omitempty"`  // The permission statement.
}

// AddPermissionResponse represents the AddPermissionResponse structure.
type AddPermissionResponse struct {
	Statement *string `json:"Statement,omitempty"` // The permission statement that's added to the function policy.
}

// AliasConfiguration Provides configuration information about a Lambda function alias.
type AliasConfiguration struct {
	AliasArn        *string                    `json:"AliasArn,omitempty"`        // The Amazon Resource Name (ARN) of the alias.
	Description     *string                    `json:"Description,omitempty"`     // A description of the alias.
	FunctionVersion *string                    `json:"FunctionVersion,omitempty"` // The function version that the alias invokes.
	Name            *string                    `json:"Name,omitempty"`            // The name of the alias.
	RevisionId      *string                    `json:"RevisionId,omitempty"`      // A unique identifier that changes when you update the alias.
	RoutingConfig   *AliasRoutingConfiguration `json:"RoutingConfig,omitempty"`   // The routing configuration of the alias.
}

// CheckpointDurableExecutionResponse The response from the CheckpointDurableExecution operation.
type CheckpointDurableExecutionResponse struct {
	CheckpointToken   *string                          `json:"CheckpointToken,omitempty"`   // A new checkpoint token to use for the next checkpoint operation. This token replaces the one prov...
	NewExecutionState *CheckpointUpdatedExecutionState `json:"NewExecutionState,omitempty"` // Updated execution state information that includes any changes that occurred since the last checkp...
}

// Concurrency represents the Concurrency structure.
type Concurrency struct {
	ReservedConcurrentExecutions *int32 `json:"ReservedConcurrentExecutions,omitempty"` // The number of concurrent executions that are reserved for this function. For more information, se...
}

// CreateCapacityProviderResponse represents the CreateCapacityProviderResponse structure.
type CreateCapacityProviderResponse struct {
	CapacityProvider *CapacityProvider `json:"CapacityProvider,omitempty"` // Information about the capacity provider that was created.
}

// CreateCodeSigningConfigResponse represents the CreateCodeSigningConfigResponse structure.
type CreateCodeSigningConfigResponse struct {
	CodeSigningConfig *CodeSigningConfig `json:"CodeSigningConfig,omitempty"` // The code signing configuration.
}

// CreateFunctionUrlConfigResponse represents the CreateFunctionUrlConfigResponse structure.
type CreateFunctionUrlConfigResponse struct {
	AuthType     FunctionUrlAuthType `json:"AuthType,omitempty"`     // The type of authentication that your function URL uses. Set to `AWS_IAM` if you want to restrict ...
	Cors         *Cors               `json:"Cors,omitempty"`         // The cross-origin resource sharing (CORS) settings for your function URL.
	CreationTime *string             `json:"CreationTime,omitempty"` // When the function URL was created, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	FunctionArn  *string             `json:"FunctionArn,omitempty"`  // The Amazon Resource Name (ARN) of your function.
	FunctionUrl  *string             `json:"FunctionUrl,omitempty"`  // The HTTP URL endpoint for your function.
	InvokeMode   InvokeMode          `json:"InvokeMode,omitempty"`   // Use one of the following options: - `BUFFERED` – This is the default option. Lambda invokes you...
}

// DeleteCapacityProviderResponse represents the DeleteCapacityProviderResponse structure.
type DeleteCapacityProviderResponse struct {
	CapacityProvider *CapacityProvider `json:"CapacityProvider,omitempty"` // Information about the deleted capacity provider.
}

// DeleteCodeSigningConfigResponse represents the DeleteCodeSigningConfigResponse structure.
type DeleteCodeSigningConfigResponse struct{}

// DeleteFunctionResponse represents the DeleteFunctionResponse structure.
type DeleteFunctionResponse struct {
	StatusCode *int32 `json:"StatusCode,omitempty"` // The HTTP status code returned by the operation.
}

// EventSourceMappingConfiguration A mapping between an Amazon Web Services resource and a Lambda function. For details, see CreateE...
type EventSourceMappingConfiguration struct {
	AmazonManagedKafkaEventSourceConfig *AmazonManagedKafkaEventSourceConfig `json:"AmazonManagedKafkaEventSourceConfig,omitempty"` // Specific configuration settings for an Amazon Managed Streaming for Apache Kafka (Amazon MSK) eve...
	BatchSize                           *int32                               `json:"BatchSize,omitempty"`                           // The maximum number of records in each batch that Lambda pulls from your stream or queue and sends...
	BisectBatchOnFunctionError          *bool                                `json:"BisectBatchOnFunctionError,omitempty"`          // (Kinesis, DynamoDB Streams, Amazon MSK, and self-managed Apache Kafka) If the function returns an...
	DestinationConfig                   *DestinationConfig                   `json:"DestinationConfig,omitempty"`                   // (Kinesis, DynamoDB Streams, Amazon MSK, and self-managed Apache Kafka) A configuration object tha...
	DocumentDBEventSourceConfig         *DocumentDBEventSourceConfig         `json:"DocumentDBEventSourceConfig,omitempty"`         // Specific configuration settings for a DocumentDB event source.
	EventSourceArn                      *string                              `json:"EventSourceArn,omitempty"`                      // The Amazon Resource Name (ARN) of the event source.
	EventSourceMappingArn               *string                              `json:"EventSourceMappingArn,omitempty"`               // The Amazon Resource Name (ARN) of the event source mapping.
	FilterCriteria                      *FilterCriteria                      `json:"FilterCriteria,omitempty"`                      // An object that defines the filter criteria that determine whether Lambda should process an event....
	FilterCriteriaError                 *FilterCriteriaError                 `json:"FilterCriteriaError,omitempty"`                 // An object that contains details about an error related to filter criteria encryption.
	FunctionArn                         *string                              `json:"FunctionArn,omitempty"`                         // The ARN of the Lambda function.
	FunctionResponseTypes               []FunctionResponseType               `json:"FunctionResponseTypes,omitempty"`               // (Kinesis, DynamoDB Streams, Amazon MSK, self-managed Apache Kafka, and Amazon SQS) A list of curr...
	KMSKeyArn                           *string                              `json:"KMSKeyArn,omitempty"`                           // The ARN of the Key Management Service (KMS) customer managed key that Lambda uses to encrypt your...
	LastModified                        *UnixTimestamp                       `json:"LastModified,omitempty"`                        // The date that the event source mapping was last updated or that its state changed.
	LastProcessingResult                *string                              `json:"LastProcessingResult,omitempty"`                // The result of the event source mapping's last processing attempt.
	MaximumBatchingWindowInSeconds      *int32                               `json:"MaximumBatchingWindowInSeconds,omitempty"`      // The maximum amount of time, in seconds, that Lambda spends gathering records before invoking the ...
	MaximumRecordAgeInSeconds           *int32                               `json:"MaximumRecordAgeInSeconds,omitempty"`           // (Kinesis, DynamoDB Streams, Amazon MSK, and self-managed Apache Kafka) Discard records older than...
	MaximumRetryAttempts                *int32                               `json:"MaximumRetryAttempts,omitempty"`                // (Kinesis, DynamoDB Streams, Amazon MSK, and self-managed Apache Kafka) Discard records after the ...
	MetricsConfig                       *EventSourceMappingMetricsConfig     `json:"MetricsConfig,omitempty"`                       // The metrics configuration for your event source. For more information, see Event source mapping m...
	ParallelizationFactor               *int32                               `json:"ParallelizationFactor,omitempty"`               // (Kinesis and DynamoDB Streams only) The number of batches to process concurrently from each shard...
	ProvisionedPollerConfig             *ProvisionedPollerConfig             `json:"ProvisionedPollerConfig,omitempty"`             // (Amazon SQS, Amazon MSK, and self-managed Apache Kafka only) The provisioned mode configuration f...
	Queues                              []string                             `json:"Queues,omitempty"`                              // (Amazon MQ) The name of the Amazon MQ broker destination queue to consume.
	ScalingConfig                       *ScalingConfig                       `json:"ScalingConfig,omitempty"`                       // (Amazon SQS only) The scaling configuration for the event source. For more information, see Confi...
	SelfManagedEventSource              *SelfManagedEventSource              `json:"SelfManagedEventSource,omitempty"`              // The self-managed Apache Kafka cluster for your event source.
	SelfManagedKafkaEventSourceConfig   *SelfManagedKafkaEventSourceConfig   `json:"SelfManagedKafkaEventSourceConfig,omitempty"`   // Specific configuration settings for a self-managed Apache Kafka event source.
	SourceAccessConfigurations          []SourceAccessConfiguration          `json:"SourceAccessConfigurations,omitempty"`          // An array of the authentication protocol, VPC components, or virtual host to secure and define you...
	StartingPosition                    EventSourcePosition                  `json:"StartingPosition,omitempty"`                    // The position in a stream from which to start reading. Required for Amazon Kinesis and Amazon Dyna...
	StartingPositionTimestamp           *UnixTimestamp                       `json:"StartingPositionTimestamp,omitempty"`           // With `StartingPosition` set to `AT_TIMESTAMP`, the time from which to start reading. `StartingPos...
	State                               *string                              `json:"State,omitempty"`                               // The state of the event source mapping. It can be one of the following: `Creating`, `Enabling`, `E...
	StateTransitionReason               *string                              `json:"StateTransitionReason,omitempty"`               // Indicates whether a user or Lambda made the last change to the event source mapping.
	Topics                              []string                             `json:"Topics,omitempty"`                              // The name of the Kafka topic.
	TumblingWindowInSeconds             *int32                               `json:"TumblingWindowInSeconds,omitempty"`             // (Kinesis and DynamoDB Streams only) The duration in seconds of a processing window for DynamoDB a...
	UUID                                *string                              `json:"UUID,omitempty"`                                // The identifier of the event source mapping.
}

// FunctionConfiguration Details about a function's configuration.
type FunctionConfiguration struct {
	Architectures              []Architecture             `json:"Architectures,omitempty"`              // The instruction set architecture that the function supports. Architecture is a string array with ...
	CapacityProviderConfig     *CapacityProviderConfig    `json:"CapacityProviderConfig,omitempty"`     // Configuration for the capacity provider that manages compute resources for Lambda functions.
	CodeSha256                 *string                    `json:"CodeSha256,omitempty"`                 // The SHA256 hash of the function's deployment package.
	CodeSize                   *int64                     `json:"CodeSize,omitempty"`                   // The size of the function's deployment package, in bytes.
	ConfigSha256               *string                    `json:"ConfigSha256,omitempty"`               // The SHA256 hash of the function configuration.
	DeadLetterConfig           *DeadLetterConfig          `json:"DeadLetterConfig,omitempty"`           // The function's dead letter queue.
	Description                *string                    `json:"Description,omitempty"`                // The function's description.
	DurableConfig              *DurableConfig             `json:"DurableConfig,omitempty"`              // The function's durable execution configuration settings, if the function is configured for durabi...
	Environment                *EnvironmentResponse       `json:"Environment,omitempty"`                // The function's environment variables. Omitted from CloudTrail logs.
	EphemeralStorage           *EphemeralStorage          `json:"EphemeralStorage,omitempty"`           // The size of the function's `/tmp` directory in MB. The default value is 512, but can be any whole...
	FileSystemConfigs          []FileSystemConfig         `json:"FileSystemConfigs,omitempty"`          // Connection settings for an Amazon EFS file system.
	FunctionArn                *string                    `json:"FunctionArn,omitempty"`                // The function's Amazon Resource Name (ARN).
	FunctionName               *string                    `json:"FunctionName,omitempty"`               // The name of the function.
	Handler                    *string                    `json:"Handler,omitempty"`                    // The function that Lambda calls to begin running your function.
	ImageConfigResponse        *ImageConfigResponse       `json:"ImageConfigResponse,omitempty"`        // The function's image configuration values.
	KMSKeyArn                  *string                    `json:"KMSKeyArn,omitempty"`                  // The ARN of the Key Management Service (KMS) customer managed key that's used to encrypt the follo...
	LastModified               *string                    `json:"LastModified,omitempty"`               // The date and time that the function was last updated, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	LastUpdateStatus           LastUpdateStatus           `json:"LastUpdateStatus,omitempty"`           // The status of the last update that was performed on the function. This is first set to `Successfu...
	LastUpdateStatusReason     *string                    `json:"LastUpdateStatusReason,omitempty"`     // The reason for the last update that was performed on the function.
	LastUpdateStatusReasonCode LastUpdateStatusReasonCode `json:"LastUpdateStatusReasonCode,omitempty"` // The reason code for the last update that was performed on the function.
	Layers                     []Layer                    `json:"Layers,omitempty"`                     // The function's layers.
	LoggingConfig              *LoggingConfig             `json:"LoggingConfig,omitempty"`              // The function's Amazon CloudWatch Logs configuration settings.
	MasterArn                  *string                    `json:"MasterArn,omitempty"`                  // For Lambda@Edge functions, the ARN of the main function.
	MemorySize                 *int32                     `json:"MemorySize,omitempty"`                 // The amount of memory available to the function at runtime.
	PackageType                PackageType                `json:"PackageType,omitempty"`                // The type of deployment package. Set to `Image` for container image and set `Zip` for .zip file ar...
	RevisionId                 *string                    `json:"RevisionId,omitempty"`                 // The latest updated revision of the function or alias.
	Role                       *string                    `json:"Role,omitempty"`                       // The function's execution role.
	Runtime                    Runtime                    `json:"Runtime,omitempty"`                    // The identifier of the function's runtime. Runtime is required if the deployment package is a .zip...
	RuntimeVersionConfig       *RuntimeVersionConfig      `json:"RuntimeVersionConfig,omitempty"`       // The ARN of the runtime and any errors that occured.
	SigningJobArn              *string                    `json:"SigningJobArn,omitempty"`              // The ARN of the signing job.
	SigningProfileVersionArn   *string                    `json:"SigningProfileVersionArn,omitempty"`   // The ARN of the signing profile version.
	SnapStart                  *SnapStartResponse         `json:"SnapStart,omitempty"`                  // Set `ApplyOn` to `PublishedVersions` to create a snapshot of the initialized execution environmen...
	State                      State                      `json:"State,omitempty"`                      // The current state of the function. When the state is `Inactive`, you can reactivate the function ...
	StateReason                *string                    `json:"StateReason,omitempty"`                // The reason for the function's current state.
	StateReasonCode            StateReasonCode            `json:"StateReasonCode,omitempty"`            // The reason code for the function's current state. When the code is `Creating`, you can't invoke o...
	TenancyConfig              *TenancyConfig             `json:"TenancyConfig,omitempty"`              // The function's tenant isolation configuration settings. Determines whether the Lambda function ru...
	Timeout                    *int32                     `json:"Timeout,omitempty"`                    // The amount of time in seconds that Lambda allows a function to run before stopping it.
	TracingConfig              *TracingConfigResponse     `json:"TracingConfig,omitempty"`              // The function's X-Ray tracing configuration.
	Version                    *string                    `json:"Version,omitempty"`                    // The version of the Lambda function.
	VpcConfig                  *VpcConfigResponse         `json:"VpcConfig,omitempty"`                  // The function's networking configuration.
}

// FunctionEventInvokeConfig represents the FunctionEventInvokeConfig structure.
type FunctionEventInvokeConfig struct {
	DestinationConfig        *DestinationConfig `json:"DestinationConfig,omitempty"`        // A destination for events after they have been sent to a function for processing. Destinations - F...
	FunctionArn              *string            `json:"FunctionArn,omitempty"`              // The Amazon Resource Name (ARN) of the function.
	LastModified             *UnixTimestamp     `json:"LastModified,omitempty"`             // The date and time that the configuration was last updated.
	MaximumEventAgeInSeconds *int32             `json:"MaximumEventAgeInSeconds,omitempty"` // The maximum age of a request that Lambda sends to a function for processing.
	MaximumRetryAttempts     *int32             `json:"MaximumRetryAttempts,omitempty"`     // The maximum number of times to retry when the function returns an error.
}

// GetAccountSettingsResponse represents the GetAccountSettingsResponse structure.
type GetAccountSettingsResponse struct {
	AccountLimit *AccountLimit `json:"AccountLimit,omitempty"` // Limits that are related to concurrency and code storage.
	AccountUsage *AccountUsage `json:"AccountUsage,omitempty"` // The number of functions and amount of storage in use.
}

// GetCapacityProviderResponse represents the GetCapacityProviderResponse structure.
type GetCapacityProviderResponse struct {
	CapacityProvider *CapacityProvider `json:"CapacityProvider,omitempty"` // Information about the capacity provider, including its configuration and current state.
}

// GetCodeSigningConfigResponse represents the GetCodeSigningConfigResponse structure.
type GetCodeSigningConfigResponse struct {
	CodeSigningConfig *CodeSigningConfig `json:"CodeSigningConfig,omitempty"` // The code signing configuration
}

// GetDurableExecutionHistoryResponse The response from the GetDurableExecutionHistory operation, containing the execution history and ...
type GetDurableExecutionHistoryResponse struct {
	Events     []Event `json:"Events,omitempty"`     // An array of execution history events, ordered chronologically unless `ReverseOrder` is set to `tr...
	NextMarker *string `json:"NextMarker,omitempty"` // If present, indicates that more history events are available. Use this value as the `Marker` para...
}

// GetDurableExecutionResponse The response from the GetDurableExecution operation, containing detailed information about the du...
type GetDurableExecutionResponse struct {
	DurableExecutionArn  *string         `json:"DurableExecutionArn,omitempty"`  // The Amazon Resource Name (ARN) of the durable execution.
	DurableExecutionName *string         `json:"DurableExecutionName,omitempty"` // The name of the durable execution. This is either the name you provided when invoking the functio...
	EndTimestamp         *UnixTimestamp  `json:"EndTimestamp,omitempty"`         // The date and time when the durable execution ended, in Unix timestamp format. This field is only ...
	Error                *ErrorObject    `json:"Error,omitempty"`                // Error information if the durable execution failed. This field is only present when the execution ...
	FunctionArn          *string         `json:"FunctionArn,omitempty"`          // The Amazon Resource Name (ARN) of the Lambda function that was invoked to start this durable exec...
	InputPayload         *string         `json:"InputPayload,omitempty"`         // The JSON input payload that was provided when the durable execution was started. For asynchronous...
	Result               *string         `json:"Result,omitempty"`               // The JSON result returned by the durable execution if it completed successfully. This field is onl...
	StartTimestamp       *UnixTimestamp  `json:"StartTimestamp,omitempty"`       // The date and time when the durable execution started, in Unix timestamp format.
	Status               ExecutionStatus `json:"Status,omitempty"`               // The current status of the durable execution. Valid values are `RUNNING`, `SUCCEEDED`, `FAILED`, `...
	TraceHeader          *TraceHeader    `json:"TraceHeader,omitempty"`          // The trace headers associated with the durable execution.
	Version              *string         `json:"Version,omitempty"`              // The version of the Lambda function that was invoked for this durable execution. This ensures that...
}

// GetDurableExecutionStateResponse The response from the GetDurableExecutionState operation, containing the current execution state ...
type GetDurableExecutionStateResponse struct {
	NextMarker *string     `json:"NextMarker,omitempty"` // If present, indicates that more operations are available. Use this value as the `Marker` paramete...
	Operations []Operation `json:"Operations,omitempty"` // An array of operations that represent the current state of the durable execution. Operations are ...
}

// GetFunctionCodeSigningConfigResponse represents the GetFunctionCodeSigningConfigResponse structure.
type GetFunctionCodeSigningConfigResponse struct {
	CodeSigningConfigArn *string `json:"CodeSigningConfigArn,omitempty"` // The The Amazon Resource Name (ARN) of the code signing configuration.
	FunctionName         *string `json:"FunctionName,omitempty"`         // The name or ARN of the Lambda function. Name formats - Function name - `MyFunction`. - Function A...
}

// GetFunctionConcurrencyResponse represents the GetFunctionConcurrencyResponse structure.
type GetFunctionConcurrencyResponse struct {
	ReservedConcurrentExecutions *int32 `json:"ReservedConcurrentExecutions,omitempty"` // The number of simultaneous executions that are reserved for the function.
}

// GetFunctionRecursionConfigResponse represents the GetFunctionRecursionConfigResponse structure.
type GetFunctionRecursionConfigResponse struct {
	RecursiveLoop RecursiveLoop `json:"RecursiveLoop,omitempty"` // If your function's recursive loop detection configuration is `Allow`, Lambda doesn't take any act...
}

// GetFunctionResponse represents the GetFunctionResponse structure.
type GetFunctionResponse struct {
	Code          *FunctionCodeLocation  `json:"Code,omitempty"`          // The deployment package of the function or version.
	Concurrency   *Concurrency           `json:"Concurrency,omitempty"`   // The function's reserved concurrency.
	Configuration *FunctionConfiguration `json:"Configuration,omitempty"` // The configuration of the function or version.
	Tags          map[string]string      `json:"Tags,omitempty"`          // The function's tags. Lambda returns tag data only if you have explicit allow permissions for lamb...
	TagsError     *TagsError             `json:"TagsError,omitempty"`     // An object that contains details about an error related to retrieving tags.
}

// GetFunctionScalingConfigResponse represents the GetFunctionScalingConfigResponse structure.
type GetFunctionScalingConfigResponse struct {
	AppliedFunctionScalingConfig   *FunctionScalingConfig `json:"AppliedFunctionScalingConfig,omitempty"`   // The scaling configuration that is currently applied to the function. This represents the actual s...
	FunctionArn                    *string                `json:"FunctionArn,omitempty"`                    // The Amazon Resource Name (ARN) of the function.
	RequestedFunctionScalingConfig *FunctionScalingConfig `json:"RequestedFunctionScalingConfig,omitempty"` // The scaling configuration that was requested for the function.
}

// GetFunctionUrlConfigResponse represents the GetFunctionUrlConfigResponse structure.
type GetFunctionUrlConfigResponse struct {
	AuthType         FunctionUrlAuthType `json:"AuthType,omitempty"`         // The type of authentication that your function URL uses. Set to `AWS_IAM` if you want to restrict ...
	Cors             *Cors               `json:"Cors,omitempty"`             // The cross-origin resource sharing (CORS) settings for your function URL.
	CreationTime     *string             `json:"CreationTime,omitempty"`     // When the function URL was created, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	FunctionArn      *string             `json:"FunctionArn,omitempty"`      // The Amazon Resource Name (ARN) of your function.
	FunctionUrl      *string             `json:"FunctionUrl,omitempty"`      // The HTTP URL endpoint for your function.
	InvokeMode       InvokeMode          `json:"InvokeMode,omitempty"`       // Use one of the following options: - `BUFFERED` – This is the default option. Lambda invokes you...
	LastModifiedTime *string             `json:"LastModifiedTime,omitempty"` // When the function URL configuration was last updated, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
}

// GetLayerVersionPolicyResponse represents the GetLayerVersionPolicyResponse structure.
type GetLayerVersionPolicyResponse struct {
	Policy     *string `json:"Policy,omitempty"`     // The policy document.
	RevisionId *string `json:"RevisionId,omitempty"` // A unique identifier for the current revision of the policy.
}

// GetLayerVersionResponse represents the GetLayerVersionResponse structure.
type GetLayerVersionResponse struct {
	CompatibleArchitectures []Architecture             `json:"CompatibleArchitectures,omitempty"` // A list of compatible instruction set architectures.
	CompatibleRuntimes      []Runtime                  `json:"CompatibleRuntimes,omitempty"`      // The layer's compatible runtimes. The following list includes deprecated runtimes. For more inform...
	Content                 *LayerVersionContentOutput `json:"Content,omitempty"`                 // Details about the layer version.
	CreatedDate             *string                    `json:"CreatedDate,omitempty"`             // The date that the layer version was created, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	Description             *string                    `json:"Description,omitempty"`             // The description of the version.
	LayerArn                *string                    `json:"LayerArn,omitempty"`                // The ARN of the layer.
	LayerVersionArn         *string                    `json:"LayerVersionArn,omitempty"`         // The ARN of the layer version.
	LicenseInfo             *string                    `json:"LicenseInfo,omitempty"`             // The layer's software license.
	Version                 *int64                     `json:"Version,omitempty"`                 // The version number.
}

// GetPolicyResponse represents the GetPolicyResponse structure.
type GetPolicyResponse struct {
	Policy     *string `json:"Policy,omitempty"`     // The resource-based policy.
	RevisionId *string `json:"RevisionId,omitempty"` // A unique identifier for the current revision of the policy.
}

// GetProvisionedConcurrencyConfigResponse represents the GetProvisionedConcurrencyConfigResponse structure.
type GetProvisionedConcurrencyConfigResponse struct {
	AllocatedProvisionedConcurrentExecutions *int32                           `json:"AllocatedProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency allocated. When a weighted alias is used during linear and ...
	AvailableProvisionedConcurrentExecutions *int32                           `json:"AvailableProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency available.
	LastModified                             *string                          `json:"LastModified,omitempty"`                             // The date and time that a user last updated the configuration, in ISO 8601 format.
	RequestedProvisionedConcurrentExecutions *int32                           `json:"RequestedProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency requested.
	Status                                   ProvisionedConcurrencyStatusEnum `json:"Status,omitempty"`                                   // The status of the allocation process.
	StatusReason                             *string                          `json:"StatusReason,omitempty"`                             // For failed allocations, the reason that provisioned concurrency could not be allocated.
}

// GetRuntimeManagementConfigResponse represents the GetRuntimeManagementConfigResponse structure.
type GetRuntimeManagementConfigResponse struct {
	FunctionArn       *string         `json:"FunctionArn,omitempty"`       // The Amazon Resource Name (ARN) of your function.
	RuntimeVersionArn *string         `json:"RuntimeVersionArn,omitempty"` // The ARN of the runtime the function is configured to use. If the runtime update mode is Manual, t...
	UpdateRuntimeOn   UpdateRuntimeOn `json:"UpdateRuntimeOn,omitempty"`   // The current runtime update mode of the function.
}

// InvocationResponse represents the InvocationResponse structure.
type InvocationResponse struct {
	DurableExecutionArn *string `json:"DurableExecutionArn,omitempty"` // The ARN of the durable execution that was started. This is returned when invoking a durable funct...
	ExecutedVersion     *string `json:"ExecutedVersion,omitempty"`     // The version of the function that executed. When you invoke a function with an alias, this indicat...
	FunctionError       *string `json:"FunctionError,omitempty"`       // If present, indicates that an error occurred during function execution. Details about the error a...
	LogResult           *string `json:"LogResult,omitempty"`           // The last 4 KB of the execution log, which is base64-encoded.
	Payload             []byte  `json:"Payload,omitempty"`             // The response from the function, or an error object.
	StatusCode          *int32  `json:"StatusCode,omitempty"`          // The HTTP status code is in the 200 range for a successful request. For the `RequestResponse` invo...
}

// InvokeAsyncResponse A success response (`202 Accepted`) indicates that the request is queued for invocation.
// Deprecated: This type is deprecated.
type InvokeAsyncResponse struct {
	Status *int32 `json:"Status,omitempty"` // The status code.
}

// InvokeWithResponseStreamResponse represents the InvokeWithResponseStreamResponse structure.
type InvokeWithResponseStreamResponse struct {
	EventStream               *interface{} `json:"EventStream,omitempty"`               // The stream of response payloads.
	ExecutedVersion           *string      `json:"ExecutedVersion,omitempty"`           // The version of the function that executed. When you invoke a function with an alias, this indicat...
	ResponseStreamContentType *string      `json:"ResponseStreamContentType,omitempty"` // The type of data the stream is returning.
	StatusCode                *int32       `json:"StatusCode,omitempty"`                // For a successful request, the HTTP status code is in the 200 range. For the `RequestResponse` inv...
}

// ListAliasesResponse represents the ListAliasesResponse structure.
type ListAliasesResponse struct {
	Aliases    []AliasConfiguration `json:"Aliases,omitempty"`    // A list of aliases.
	NextMarker *string              `json:"NextMarker,omitempty"` // The pagination token that's included if more results are available.
}

// ListCapacityProvidersResponse represents the ListCapacityProvidersResponse structure.
type ListCapacityProvidersResponse struct {
	CapacityProviders []CapacityProvider `json:"CapacityProviders,omitempty"` // A list of capacity providers in your account.
	NextMarker        *string            `json:"NextMarker,omitempty"`        // The pagination token that's included if more results are available.
}

// ListCodeSigningConfigsResponse represents the ListCodeSigningConfigsResponse structure.
type ListCodeSigningConfigsResponse struct {
	CodeSigningConfigs []CodeSigningConfig `json:"CodeSigningConfigs,omitempty"` // The code signing configurations
	NextMarker         *string             `json:"NextMarker,omitempty"`         // The pagination token that's included if more results are available.
}

// ListDurableExecutionsByFunctionResponse The response from the ListDurableExecutionsByFunction operation, containing a list of durable exe...
type ListDurableExecutionsByFunctionResponse struct {
	DurableExecutions []Execution `json:"DurableExecutions,omitempty"` // List of durable execution summaries matching the filter criteria.
	NextMarker        *string     `json:"NextMarker,omitempty"`        // Pagination token for retrieving additional results. Present only if there are more results availa...
}

// ListEventSourceMappingsResponse represents the ListEventSourceMappingsResponse structure.
type ListEventSourceMappingsResponse struct {
	EventSourceMappings []EventSourceMappingConfiguration `json:"EventSourceMappings,omitempty"` // A list of event source mappings.
	NextMarker          *string                           `json:"NextMarker,omitempty"`          // A pagination token that's returned when the response doesn't contain all event source mappings.
}

// ListFunctionEventInvokeConfigsResponse represents the ListFunctionEventInvokeConfigsResponse structure.
type ListFunctionEventInvokeConfigsResponse struct {
	FunctionEventInvokeConfigs []FunctionEventInvokeConfig `json:"FunctionEventInvokeConfigs,omitempty"` // A list of configurations.
	NextMarker                 *string                     `json:"NextMarker,omitempty"`                 // The pagination token that's included if more results are available.
}

// ListFunctionUrlConfigsResponse represents the ListFunctionUrlConfigsResponse structure.
type ListFunctionUrlConfigsResponse struct {
	FunctionUrlConfigs []FunctionUrlConfig `json:"FunctionUrlConfigs,omitempty"` // A list of function URL configurations.
	NextMarker         *string             `json:"NextMarker,omitempty"`         // The pagination token that's included if more results are available.
}

// ListFunctionVersionsByCapacityProviderResponse represents the ListFunctionVersionsByCapacityProviderResponse structure.
type ListFunctionVersionsByCapacityProviderResponse struct {
	CapacityProviderArn *string                                      `json:"CapacityProviderArn,omitempty"` // The Amazon Resource Name (ARN) of the capacity provider.
	FunctionVersions    []FunctionVersionsByCapacityProviderListItem `json:"FunctionVersions,omitempty"`    // A list of function versions that use the specified capacity provider.
	NextMarker          *string                                      `json:"NextMarker,omitempty"`          // The pagination token that's included if more results are available.
}

// ListFunctionsByCodeSigningConfigResponse represents the ListFunctionsByCodeSigningConfigResponse structure.
type ListFunctionsByCodeSigningConfigResponse struct {
	FunctionArns []string `json:"FunctionArns,omitempty"` // The function ARNs.
	NextMarker   *string  `json:"NextMarker,omitempty"`   // The pagination token that's included if more results are available.
}

// ListFunctionsResponse A list of Lambda functions.
type ListFunctionsResponse struct {
	Functions  []FunctionConfiguration `json:"Functions,omitempty"`  // A list of Lambda functions.
	NextMarker *string                 `json:"NextMarker,omitempty"` // The pagination token that's included if more results are available.
}

// ListLayerVersionsResponse represents the ListLayerVersionsResponse structure.
type ListLayerVersionsResponse struct {
	LayerVersions []LayerVersionsListItem `json:"LayerVersions,omitempty"` // A list of versions.
	NextMarker    *string                 `json:"NextMarker,omitempty"`    // A pagination token returned when the response doesn't contain all versions.
}

// ListLayersResponse represents the ListLayersResponse structure.
type ListLayersResponse struct {
	Layers     []LayersListItem `json:"Layers,omitempty"`     // A list of function layers.
	NextMarker *string          `json:"NextMarker,omitempty"` // A pagination token returned when the response doesn't contain all layers.
}

// ListProvisionedConcurrencyConfigsResponse represents the ListProvisionedConcurrencyConfigsResponse structure.
type ListProvisionedConcurrencyConfigsResponse struct {
	NextMarker                    *string                                `json:"NextMarker,omitempty"`                    // The pagination token that's included if more results are available.
	ProvisionedConcurrencyConfigs []ProvisionedConcurrencyConfigListItem `json:"ProvisionedConcurrencyConfigs,omitempty"` // A list of provisioned concurrency configurations.
}

// ListTagsResponse represents the ListTagsResponse structure.
type ListTagsResponse struct {
	Tags map[string]string `json:"Tags,omitempty"` // The function's tags.
}

// ListVersionsByFunctionResponse represents the ListVersionsByFunctionResponse structure.
type ListVersionsByFunctionResponse struct {
	NextMarker *string                 `json:"NextMarker,omitempty"` // The pagination token that's included if more results are available.
	Versions   []FunctionConfiguration `json:"Versions,omitempty"`   // A list of Lambda function versions.
}

// PublishLayerVersionResponse represents the PublishLayerVersionResponse structure.
type PublishLayerVersionResponse struct {
	CompatibleArchitectures []Architecture             `json:"CompatibleArchitectures,omitempty"` // A list of compatible instruction set architectures.
	CompatibleRuntimes      []Runtime                  `json:"CompatibleRuntimes,omitempty"`      // The layer's compatible runtimes. The following list includes deprecated runtimes. For more inform...
	Content                 *LayerVersionContentOutput `json:"Content,omitempty"`                 // Details about the layer version.
	CreatedDate             *string                    `json:"CreatedDate,omitempty"`             // The date that the layer version was created, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	Description             *string                    `json:"Description,omitempty"`             // The description of the version.
	LayerArn                *string                    `json:"LayerArn,omitempty"`                // The ARN of the layer.
	LayerVersionArn         *string                    `json:"LayerVersionArn,omitempty"`         // The ARN of the layer version.
	LicenseInfo             *string                    `json:"LicenseInfo,omitempty"`             // The layer's software license.
	Version                 *int64                     `json:"Version,omitempty"`                 // The version number.
}

// PutFunctionCodeSigningConfigResponse represents the PutFunctionCodeSigningConfigResponse structure.
type PutFunctionCodeSigningConfigResponse struct {
	CodeSigningConfigArn *string `json:"CodeSigningConfigArn,omitempty"` // The The Amazon Resource Name (ARN) of the code signing configuration.
	FunctionName         *string `json:"FunctionName,omitempty"`         // The name or ARN of the Lambda function. Name formats - Function name - `MyFunction`. - Function A...
}

// PutFunctionRecursionConfigResponse represents the PutFunctionRecursionConfigResponse structure.
type PutFunctionRecursionConfigResponse struct {
	RecursiveLoop RecursiveLoop `json:"RecursiveLoop,omitempty"` // The status of your function's recursive loop detection configuration. When this value is set to `...
}

// PutFunctionScalingConfigResponse represents the PutFunctionScalingConfigResponse structure.
type PutFunctionScalingConfigResponse struct {
	FunctionState State `json:"FunctionState,omitempty"` // The current state of the function after applying the scaling configuration.
}

// PutProvisionedConcurrencyConfigResponse represents the PutProvisionedConcurrencyConfigResponse structure.
type PutProvisionedConcurrencyConfigResponse struct {
	AllocatedProvisionedConcurrentExecutions *int32                           `json:"AllocatedProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency allocated. When a weighted alias is used during linear and ...
	AvailableProvisionedConcurrentExecutions *int32                           `json:"AvailableProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency available.
	LastModified                             *string                          `json:"LastModified,omitempty"`                             // The date and time that a user last updated the configuration, in ISO 8601 format.
	RequestedProvisionedConcurrentExecutions *int32                           `json:"RequestedProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency requested.
	Status                                   ProvisionedConcurrencyStatusEnum `json:"Status,omitempty"`                                   // The status of the allocation process.
	StatusReason                             *string                          `json:"StatusReason,omitempty"`                             // For failed allocations, the reason that provisioned concurrency could not be allocated.
}

// PutRuntimeManagementConfigResponse represents the PutRuntimeManagementConfigResponse structure.
type PutRuntimeManagementConfigResponse struct {
	FunctionArn       *string         `json:"FunctionArn,omitempty"`       // The ARN of the function
	RuntimeVersionArn *string         `json:"RuntimeVersionArn,omitempty"` // The ARN of the runtime the function is configured to use. If the runtime update mode is manual, t...
	UpdateRuntimeOn   UpdateRuntimeOn `json:"UpdateRuntimeOn,omitempty"`   // The runtime update mode.
}

// SendDurableExecutionCallbackFailureResponse represents the SendDurableExecutionCallbackFailureResponse structure.
type SendDurableExecutionCallbackFailureResponse struct{}

// SendDurableExecutionCallbackHeartbeatResponse represents the SendDurableExecutionCallbackHeartbeatResponse structure.
type SendDurableExecutionCallbackHeartbeatResponse struct{}

// SendDurableExecutionCallbackSuccessResponse represents the SendDurableExecutionCallbackSuccessResponse structure.
type SendDurableExecutionCallbackSuccessResponse struct{}

// StopDurableExecutionResponse represents the StopDurableExecutionResponse structure.
type StopDurableExecutionResponse struct {
	StopTimestamp *UnixTimestamp `json:"StopTimestamp,omitempty"` // The timestamp when the execution was stopped (ISO 8601 format).
}

// UpdateCapacityProviderResponse represents the UpdateCapacityProviderResponse structure.
type UpdateCapacityProviderResponse struct {
	CapacityProvider *CapacityProvider `json:"CapacityProvider,omitempty"` // Information about the updated capacity provider.
}

// UpdateCodeSigningConfigResponse represents the UpdateCodeSigningConfigResponse structure.
type UpdateCodeSigningConfigResponse struct {
	CodeSigningConfig *CodeSigningConfig `json:"CodeSigningConfig,omitempty"` // The code signing configuration
}

// UpdateFunctionUrlConfigResponse represents the UpdateFunctionUrlConfigResponse structure.
type UpdateFunctionUrlConfigResponse struct {
	AuthType         FunctionUrlAuthType `json:"AuthType,omitempty"`         // The type of authentication that your function URL uses. Set to `AWS_IAM` if you want to restrict ...
	Cors             *Cors               `json:"Cors,omitempty"`             // The cross-origin resource sharing (CORS) settings for your function URL.
	CreationTime     *string             `json:"CreationTime,omitempty"`     // When the function URL was created, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	FunctionArn      *string             `json:"FunctionArn,omitempty"`      // The Amazon Resource Name (ARN) of your function.
	FunctionUrl      *string             `json:"FunctionUrl,omitempty"`      // The HTTP URL endpoint for your function.
	InvokeMode       InvokeMode          `json:"InvokeMode,omitempty"`       // Use one of the following options: - `BUFFERED` – This is the default option. Lambda invokes you...
	LastModifiedTime *string             `json:"LastModifiedTime,omitempty"` // When the function URL configuration was last updated, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
}

// AccountLimit Limits that are related to concurrency and storage. All file and storage sizes are in bytes.
type AccountLimit struct {
	CodeSizeUnzipped               *int64 `json:"CodeSizeUnzipped,omitempty"`               // The maximum size of a function's deployment package and layers when they're extracted.
	CodeSizeZipped                 *int64 `json:"CodeSizeZipped,omitempty"`                 // The maximum size of a deployment package when it's uploaded directly to Lambda. Use Amazon S3 for...
	ConcurrentExecutions           *int32 `json:"ConcurrentExecutions,omitempty"`           // The maximum number of simultaneous function executions.
	TotalCodeSize                  *int64 `json:"TotalCodeSize,omitempty"`                  // The amount of storage space that you can use for all deployment packages and layer archives.
	UnreservedConcurrentExecutions *int32 `json:"UnreservedConcurrentExecutions,omitempty"` // The maximum number of simultaneous function executions, minus the capacity that's reserved for in...
}

// AccountUsage The number of functions and amount of storage in use.
type AccountUsage struct {
	FunctionCount *int64 `json:"FunctionCount,omitempty"` // The number of Lambda functions.
	TotalCodeSize *int64 `json:"TotalCodeSize,omitempty"` // The amount of storage space, in bytes, that's being used by deployment packages and layer archives.
}

// AliasRoutingConfiguration The traffic-shifting configuration of a Lambda function alias.
type AliasRoutingConfiguration struct {
	AdditionalVersionWeights map[string]string `json:"AdditionalVersionWeights,omitempty"` // The second version, and the percentage of traffic that's routed to it.
}

// AllowedPublishers List of signing profiles that can sign a code package.
type AllowedPublishers struct {
	SigningProfileVersionArns []string `json:"SigningProfileVersionArns,omitempty"` // The Amazon Resource Name (ARN) for each of the signing profiles. A signing profile defines a trus...
}

// AmazonManagedKafkaEventSourceConfig Specific configuration settings for an Amazon Managed Streaming for Apache Kafka (Amazon MSK) eve...
type AmazonManagedKafkaEventSourceConfig struct {
	ConsumerGroupId      *string                    `json:"ConsumerGroupId,omitempty"`      // The identifier for the Kafka consumer group to join. The consumer group ID must be unique among a...
	SchemaRegistryConfig *KafkaSchemaRegistryConfig `json:"SchemaRegistryConfig,omitempty"` // Specific configuration settings for a Kafka schema registry.
}

// CallbackDetails Contains details about a callback operation in a durable execution, including the callback token ...
type CallbackDetails struct {
	CallbackId *string      `json:"CallbackId,omitempty"` // The callback ID. Callback IDs are generated by the `DurableContext` when a durable function calls...
	Error      *ErrorObject `json:"Error,omitempty"`      // An error object that contains details about the failure.
	Result     *string      `json:"Result,omitempty"`     // The response payload from the callback operation as a string.
}

// CallbackFailedDetails Contains details about a failed callback operation, including error information and the reason fo...
type CallbackFailedDetails struct {
	Error *EventError `json:"Error,omitempty"` // An error object that contains details about the failure.
}

// CallbackStartedDetails Contains details about a callback operation that has started, including timing information and ca...
type CallbackStartedDetails struct {
	CallbackId       *string `json:"CallbackId,omitempty"`       // The callback ID. Callback IDs are generated by the `DurableContext` when a durable function calls...
	HeartbeatTimeout *int32  `json:"HeartbeatTimeout,omitempty"` // The heartbeat timeout value, in seconds.
	Timeout          *int32  `json:"Timeout,omitempty"`          // The timeout value, in seconds.
}

// CallbackSucceededDetails Contains details about a successfully completed callback operation, including the result data and...
type CallbackSucceededDetails struct {
	Result *EventResult `json:"Result,omitempty"` // The response payload from the successful operation.
}

// CallbackTimedOutDetails Contains details about a callback operation that timed out, including timeout duration and any pa...
type CallbackTimedOutDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about the callback timeout.
}

// CapacityProvider A capacity provider manages compute resources for Lambda functions.
type CapacityProvider struct {
	CapacityProviderArn           *string                            `json:"CapacityProviderArn,omitempty"`           // The Amazon Resource Name (ARN) of the capacity provider.
	CapacityProviderScalingConfig *CapacityProviderScalingConfig     `json:"CapacityProviderScalingConfig,omitempty"` // The scaling configuration for the capacity provider.
	InstanceRequirements          *InstanceRequirements              `json:"InstanceRequirements,omitempty"`          // The instance requirements for compute resources managed by the capacity provider.
	KmsKeyArn                     *string                            `json:"KmsKeyArn,omitempty"`                     // The ARN of the KMS key used to encrypt the capacity provider's resources.
	LastModified                  *string                            `json:"LastModified,omitempty"`                  // The date and time when the capacity provider was last modified.
	PermissionsConfig             *CapacityProviderPermissionsConfig `json:"PermissionsConfig,omitempty"`             // The permissions configuration for the capacity provider.
	State                         CapacityProviderState              `json:"State,omitempty"`                         // The current state of the capacity provider.
	VpcConfig                     *CapacityProviderVpcConfig         `json:"VpcConfig,omitempty"`                     // The VPC configuration for the capacity provider.
}

// CapacityProviderConfig Configuration for the capacity provider that manages compute resources for Lambda functions.
type CapacityProviderConfig struct {
	LambdaManagedInstancesCapacityProviderConfig *LambdaManagedInstancesCapacityProviderConfig `json:"LambdaManagedInstancesCapacityProviderConfig,omitempty"` // Configuration for Lambda-managed instances used by the capacity provider.
}

// CapacityProviderPermissionsConfig Configuration that specifies the permissions required for the capacity provider to manage compute...
type CapacityProviderPermissionsConfig struct {
	CapacityProviderOperatorRoleArn *string `json:"CapacityProviderOperatorRoleArn,omitempty"` // The ARN of the IAM role that the capacity provider uses to manage compute instances and other Ama...
}

// CapacityProviderScalingConfig Configuration that defines how the capacity provider scales compute instances based on demand and...
type CapacityProviderScalingConfig struct {
	MaxVCpuCount    *int32                        `json:"MaxVCpuCount,omitempty"`    // The maximum number of vCPUs that the capacity provider can provision across all compute instances.
	ScalingMode     CapacityProviderScalingMode   `json:"ScalingMode,omitempty"`     // The scaling mode that determines how the capacity provider responds to changes in demand.
	ScalingPolicies []TargetTrackingScalingPolicy `json:"ScalingPolicies,omitempty"` // A list of scaling policies that define how the capacity provider scales compute instances based o...
}

// CapacityProviderVpcConfig VPC configuration that specifies the network settings for compute instances managed by the capaci...
type CapacityProviderVpcConfig struct {
	SecurityGroupIds []string `json:"SecurityGroupIds,omitempty"` // A list of security group IDs that control network access for compute instances managed by the cap...
	SubnetIds        []string `json:"SubnetIds,omitempty"`        // A list of subnet IDs where the capacity provider launches compute instances.
}

// ChainedInvokeDetails Contains details about a chained function invocation in a durable execution, including the target...
type ChainedInvokeDetails struct {
	Error  *ErrorObject `json:"Error,omitempty"`  // Details about the chained invocation failure.
	Result *string      `json:"Result,omitempty"` // The response payload from the chained invocation.
}

// ChainedInvokeFailedDetails Contains details about a failed chained function invocation, including error information and fail...
type ChainedInvokeFailedDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about the chained invocation failure.
}

// ChainedInvokeStartedDetails Contains details about a chained function invocation that has started execution, including start ...
type ChainedInvokeStartedDetails struct {
	DurableExecutionArn *string     `json:"DurableExecutionArn,omitempty"` // The Amazon Resource Name (ARN) that identifies the durable execution.
	ExecutedVersion     *string     `json:"ExecutedVersion,omitempty"`     // The version of the function that was executed.
	FunctionName        *string     `json:"FunctionName,omitempty"`        // The name or ARN of the Lambda function being invoked.
	Input               *EventInput `json:"Input,omitempty"`               // The JSON input payload provided to the chained invocation.
	TenantId            *string     `json:"TenantId,omitempty"`            // The tenant identifier for the chained invocation.
}

// ChainedInvokeStoppedDetails Details about a chained invocation that was stopped.
type ChainedInvokeStoppedDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about why the chained invocation stopped.
}

// ChainedInvokeSucceededDetails Details about a chained invocation that succeeded.
type ChainedInvokeSucceededDetails struct {
	Result *EventResult `json:"Result,omitempty"` // The response payload from the successful operation.
}

// ChainedInvokeTimedOutDetails Details about a chained invocation that timed out.
type ChainedInvokeTimedOutDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about the chained invocation timeout.
}

// CheckpointUpdatedExecutionState Contains operations that have been updated since the last checkpoint, such as completed asynchron...
type CheckpointUpdatedExecutionState struct {
	NextMarker *string     `json:"NextMarker,omitempty"` // Indicates that more results are available. Use this value in a subsequent call to retrieve the ne...
	Operations []Operation `json:"Operations,omitempty"` // A list of operations that have been updated since the last checkpoint.
}

// CodeSigningConfig Details about a Code signing configuration.
type CodeSigningConfig struct {
	AllowedPublishers    *AllowedPublishers   `json:"AllowedPublishers,omitempty"`    // List of allowed publishers.
	CodeSigningConfigArn *string              `json:"CodeSigningConfigArn,omitempty"` // The Amazon Resource Name (ARN) of the Code signing configuration.
	CodeSigningConfigId  *string              `json:"CodeSigningConfigId,omitempty"`  // Unique identifer for the Code signing configuration.
	CodeSigningPolicies  *CodeSigningPolicies `json:"CodeSigningPolicies,omitempty"`  // The code signing policy controls the validation failure action for signature mismatch or expiry.
	Description          *string              `json:"Description,omitempty"`          // Code signing configuration description.
	LastModified         *string              `json:"LastModified,omitempty"`         // The date and time that the Code signing configuration was last modified, in ISO-8601 format (YYYY...
}

// CodeSigningPolicies Code signing configuration policies specify the validation failure action for signature mismatch ...
type CodeSigningPolicies struct {
	UntrustedArtifactOnDeployment CodeSigningPolicy `json:"UntrustedArtifactOnDeployment,omitempty"` // Code signing configuration policy for deployment validation failure. If you set the policy to `En...
}

// ContextDetails Details about a durable execution context.
type ContextDetails struct {
	Error          *ErrorObject `json:"Error,omitempty"`          // Details about the context failure.
	ReplayChildren *bool        `json:"ReplayChildren,omitempty"` // Whether the state data of child operations of this completed context should be included in the in...
	Result         *string      `json:"Result,omitempty"`         // The response payload from the context.
}

// ContextFailedDetails Details about a context that failed.
type ContextFailedDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about the context failure.
}

// ContextStartedDetails Details about a context that has started.
type ContextStartedDetails struct{}

// ContextSucceededDetails Details about a context that succeeded.
type ContextSucceededDetails struct {
	Result *EventResult `json:"Result,omitempty"` // The JSON response payload from the successful context.
}

// Cors The cross-origin resource sharing (CORS) settings for your Lambda function URL. Use CORS to grant...
type Cors struct {
	AllowCredentials *bool    `json:"AllowCredentials,omitempty"` // Whether to allow cookies or other credentials in requests to your function URL. The default is `f...
	AllowHeaders     []string `json:"AllowHeaders,omitempty"`     // The HTTP headers that origins can include in requests to your function URL. For example: `Date`, ...
	AllowMethods     []string `json:"AllowMethods,omitempty"`     // The HTTP methods that are allowed when calling your function URL. For example: `GET`, `POST`, `DE...
	AllowOrigins     []string `json:"AllowOrigins,omitempty"`     // The origins that can access your function URL. You can list any number of specific origins, separ...
	ExposeHeaders    []string `json:"ExposeHeaders,omitempty"`    // The HTTP headers in your function response that you want to expose to origins that call your func...
	MaxAge           *int32   `json:"MaxAge,omitempty"`           // The maximum amount of time, in seconds, that web browsers can cache results of a preflight reques...
}

// DeadLetterConfig The dead-letter queue for failed asynchronous invocations.
type DeadLetterConfig struct {
	TargetArn *string `json:"TargetArn,omitempty"` // The Amazon Resource Name (ARN) of an Amazon SQS queue or Amazon SNS topic.
}

// DestinationConfig A configuration object that specifies the destination of an event after Lambda processes it. For ...
type DestinationConfig struct {
	OnFailure *OnFailure `json:"OnFailure,omitempty"` // The destination configuration for failed invocations.
	OnSuccess *OnSuccess `json:"OnSuccess,omitempty"` // The destination configuration for successful invocations. Not supported in `CreateEventSourceMapp...
}

// DocumentDBEventSourceConfig Specific configuration settings for a DocumentDB event source.
type DocumentDBEventSourceConfig struct {
	CollectionName *string      `json:"CollectionName,omitempty"` // The name of the collection to consume within the database. If you do not specify a collection, La...
	DatabaseName   *string      `json:"DatabaseName,omitempty"`   // The name of the database to consume within the DocumentDB cluster.
	FullDocument   FullDocument `json:"FullDocument,omitempty"`   // Determines what DocumentDB sends to your event stream during document update operations. If set t...
}

// DurableConfig Configuration settings for durable functions, including execution timeout and retention period fo...
type DurableConfig struct {
	ExecutionTimeout      *int32 `json:"ExecutionTimeout,omitempty"`      // The maximum time (in seconds) that a durable execution can run before timing out. This timeout ap...
	RetentionPeriodInDays *int32 `json:"RetentionPeriodInDays,omitempty"` // The number of days to retain execution history after a durable execution completes. After this pe...
}

// EnvironmentError Error messages for environment variables that couldn't be applied.
type EnvironmentError struct {
	ErrorCode *string `json:"ErrorCode,omitempty"` // The error code.
	Message   *string `json:"Message,omitempty"`   // The error message.
}

// EnvironmentResponse The results of an operation to update or read environment variables. If the operation succeeds, t...
type EnvironmentResponse struct {
	Error     *EnvironmentError `json:"Error,omitempty"`     // Error messages for environment variables that couldn't be applied.
	Variables map[string]string `json:"Variables,omitempty"` // Environment variable key-value pairs. Omitted from CloudTrail logs.
}

// EphemeralStorage The size of the function's `/tmp` directory in MB. The default value is 512, but can be any whole...
type EphemeralStorage struct {
	Size *int32 `json:"Size,omitempty"` // The size of the function's `/tmp` directory.
}

// ErrorObject An object that contains error information.
type ErrorObject struct {
	ErrorData    *string  `json:"ErrorData,omitempty"`    // Machine-readable error data.
	ErrorMessage *string  `json:"ErrorMessage,omitempty"` // A human-readable error message.
	ErrorType    *string  `json:"ErrorType,omitempty"`    // The error type.
	StackTrace   []string `json:"StackTrace,omitempty"`   // Stack trace information for the error.
}

// Event An event that occurred during the execution of a durable function.
type Event struct {
	CallbackFailedDetails         *CallbackFailedDetails         `json:"CallbackFailedDetails,omitempty"`
	CallbackStartedDetails        *CallbackStartedDetails        `json:"CallbackStartedDetails,omitempty"`
	CallbackSucceededDetails      *CallbackSucceededDetails      `json:"CallbackSucceededDetails,omitempty"`
	CallbackTimedOutDetails       *CallbackTimedOutDetails       `json:"CallbackTimedOutDetails,omitempty"`
	ChainedInvokeFailedDetails    *ChainedInvokeFailedDetails    `json:"ChainedInvokeFailedDetails,omitempty"`
	ChainedInvokeStartedDetails   *ChainedInvokeStartedDetails   `json:"ChainedInvokeStartedDetails,omitempty"`
	ChainedInvokeStoppedDetails   *ChainedInvokeStoppedDetails   `json:"ChainedInvokeStoppedDetails,omitempty"`   // Details about a chained invocation that was stopped.
	ChainedInvokeSucceededDetails *ChainedInvokeSucceededDetails `json:"ChainedInvokeSucceededDetails,omitempty"` // Details about a chained invocation that succeeded.
	ChainedInvokeTimedOutDetails  *ChainedInvokeTimedOutDetails  `json:"ChainedInvokeTimedOutDetails,omitempty"`  // Details about a chained invocation that timed out.
	ContextFailedDetails          *ContextFailedDetails          `json:"ContextFailedDetails,omitempty"`          // Details about a context that failed.
	ContextStartedDetails         *ContextStartedDetails         `json:"ContextStartedDetails,omitempty"`         // Details about a context that started.
	ContextSucceededDetails       *ContextSucceededDetails       `json:"ContextSucceededDetails,omitempty"`       // Details about a context that succeeded.
	EventId                       *int32                         `json:"EventId,omitempty"`                       // The unique identifier for this event. Event IDs increment sequentially.
	EventTimestamp                *UnixTimestamp                 `json:"EventTimestamp,omitempty"`                // The date and time when this event occurred, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	EventType                     EventType                      `json:"EventType,omitempty"`                     // The type of event that occurred.
	ExecutionFailedDetails        *ExecutionFailedDetails        `json:"ExecutionFailedDetails,omitempty"`        // Details about an execution that failed.
	ExecutionStartedDetails       *ExecutionStartedDetails       `json:"ExecutionStartedDetails,omitempty"`       // Details about an execution that started.
	ExecutionStoppedDetails       *ExecutionStoppedDetails       `json:"ExecutionStoppedDetails,omitempty"`       // Details about an execution that was stopped.
	ExecutionSucceededDetails     *ExecutionSucceededDetails     `json:"ExecutionSucceededDetails,omitempty"`     // Details about an execution that succeeded.
	ExecutionTimedOutDetails      *ExecutionTimedOutDetails      `json:"ExecutionTimedOutDetails,omitempty"`      // Details about an execution that timed out.
	Id                            *string                        `json:"Id,omitempty"`                            // The unique identifier for this operation.
	InvocationCompletedDetails    *InvocationCompletedDetails    `json:"InvocationCompletedDetails,omitempty"`    // Details about a function invocation that completed.
	Name                          *string                        `json:"Name,omitempty"`                          // The customer-provided name for this operation.
	ParentId                      *string                        `json:"ParentId,omitempty"`                      // The unique identifier of the parent operation, if this operation is running within a child context.
	StepFailedDetails             *StepFailedDetails             `json:"StepFailedDetails,omitempty"`             // Details about a step that failed.
	StepStartedDetails            *StepStartedDetails            `json:"StepStartedDetails,omitempty"`            // Details about a step that started.
	StepSucceededDetails          *StepSucceededDetails          `json:"StepSucceededDetails,omitempty"`          // Details about a step that succeeded.
	SubType                       *string                        `json:"SubType,omitempty"`                       // The subtype of the event, providing additional categorization.
	WaitCancelledDetails          *WaitCancelledDetails          `json:"WaitCancelledDetails,omitempty"`          // Details about a wait operation that was cancelled.
	WaitStartedDetails            *WaitStartedDetails            `json:"WaitStartedDetails,omitempty"`            // Details about a wait operation that started.
	WaitSucceededDetails          *WaitSucceededDetails          `json:"WaitSucceededDetails,omitempty"`          // Details about a wait operation that succeeded.
}

// EventError Error information for an event.
type EventError struct {
	Payload   *ErrorObject `json:"Payload,omitempty"`   // The error payload.
	Truncated *bool        `json:"Truncated,omitempty"` // Indicates if the error payload was truncated due to size limits.
}

// EventInput Input information for an event.
type EventInput struct {
	Payload   *string `json:"Payload,omitempty"`   // The input payload.
	Truncated *bool   `json:"Truncated,omitempty"` // Indicates if the error payload was truncated due to size limits.
}

// EventResult Result information for an event.
type EventResult struct {
	Payload   *string `json:"Payload,omitempty"`   // The result payload.
	Truncated *bool   `json:"Truncated,omitempty"` // Indicates if the error payload was truncated due to size limits.
}

// EventSourceMappingMetricsConfig The metrics configuration for your event source. Use this configuration object to define which me...
type EventSourceMappingMetricsConfig struct {
	Metrics []EventSourceMappingMetric `json:"Metrics,omitempty"` // The metrics you want your event source mapping to produce. Include `EventCount` to receive event ...
}

// Execution Information about a durable execution.
type Execution struct {
	DurableExecutionArn  *string         `json:"DurableExecutionArn,omitempty"`  // The Amazon Resource Name (ARN) of the durable execution, if this execution is a durable execution.
	DurableExecutionName *string         `json:"DurableExecutionName,omitempty"` // The unique name of the durable execution, if one was provided when the execution was started.
	EndTimestamp         *UnixTimestamp  `json:"EndTimestamp,omitempty"`         // The date and time when the durable execution ended, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	FunctionArn          *string         `json:"FunctionArn,omitempty"`          // The Amazon Resource Name (ARN) of the Lambda function.
	StartTimestamp       *UnixTimestamp  `json:"StartTimestamp,omitempty"`       // The date and time when the durable execution started, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	Status               ExecutionStatus `json:"Status,omitempty"`               // The current status of the durable execution.
}

// ExecutionDetails Details about a durable execution.
type ExecutionDetails struct {
	InputPayload *string `json:"InputPayload,omitempty"` // The original input payload provided for the durable execution.
}

// ExecutionFailedDetails Details about a failed durable execution.
type ExecutionFailedDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about the execution failure.
}

// ExecutionStartedDetails Details about a durable execution that started.
type ExecutionStartedDetails struct {
	ExecutionTimeout *int32      `json:"ExecutionTimeout,omitempty"` // The maximum amount of time that the durable execution is allowed to run, in seconds.
	Input            *EventInput `json:"Input,omitempty"`            // The input payload provided for the durable execution.
}

// ExecutionStoppedDetails Details about a durable execution that stopped.
type ExecutionStoppedDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about why the execution stopped.
}

// ExecutionSucceededDetails Details about a durable execution that succeeded.
type ExecutionSucceededDetails struct {
	Result *EventResult `json:"Result,omitempty"` // The response payload from the successful operation.
}

// ExecutionTimedOutDetails Details about a durable execution that timed out.
type ExecutionTimedOutDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about the execution timeout.
}

// FileSystemConfig Details about the connection between a Lambda function and an Amazon EFS file system.
type FileSystemConfig struct {
	Arn            *string `json:"Arn,omitempty"`            // The Amazon Resource Name (ARN) of the Amazon EFS access point that provides access to the file sy...
	LocalMountPath *string `json:"LocalMountPath,omitempty"` // The path where the function can access the file system, starting with `/mnt/`.
}

// Filter A structure within a `FilterCriteria` object that defines an event filtering pattern.
type Filter struct {
	Pattern *string `json:"Pattern,omitempty"` // A filter pattern. For more information on the syntax of a filter pattern, see Filter rule syntax.
}

// FilterCriteria An object that contains the filters for an event source.
type FilterCriteria struct {
	Filters []Filter `json:"Filters,omitempty"` // A list of filters.
}

// FilterCriteriaError An object that contains details about an error related to filter criteria encryption.
type FilterCriteriaError struct {
	ErrorCode *string `json:"ErrorCode,omitempty"` // The KMS exception that resulted from filter criteria encryption or decryption.
	Message   *string `json:"Message,omitempty"`   // The error message.
}

// FunctionCodeLocation Details about a function's deployment package.
type FunctionCodeLocation struct {
	ImageUri         *string `json:"ImageUri,omitempty"`         // URI of a container image in the Amazon ECR registry.
	Location         *string `json:"Location,omitempty"`         // A presigned URL that you can use to download the deployment package.
	RepositoryType   *string `json:"RepositoryType,omitempty"`   // The service that's hosting the file.
	ResolvedImageUri *string `json:"ResolvedImageUri,omitempty"` // The resolved URI for the image.
	SourceKMSKeyArn  *string `json:"SourceKMSKeyArn,omitempty"`  // The ARN of the Key Management Service (KMS) customer managed key that's used to encrypt your func...
}

// FunctionScalingConfig Configuration that defines the scaling behavior for a Lambda Managed Instances function, includin...
type FunctionScalingConfig struct {
	MaxExecutionEnvironments *int32 `json:"MaxExecutionEnvironments,omitempty"` // The maximum number of execution environments that can be provisioned for the function.
	MinExecutionEnvironments *int32 `json:"MinExecutionEnvironments,omitempty"` // The minimum number of execution environments to maintain for the function.
}

// FunctionUrlConfig Details about a Lambda function URL.
type FunctionUrlConfig struct {
	AuthType         FunctionUrlAuthType `json:"AuthType,omitempty"`         // The type of authentication that your function URL uses. Set to `AWS_IAM` if you want to restrict ...
	Cors             *Cors               `json:"Cors,omitempty"`             // The cross-origin resource sharing (CORS) settings for your function URL.
	CreationTime     *string             `json:"CreationTime,omitempty"`     // When the function URL was created, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	FunctionArn      *string             `json:"FunctionArn,omitempty"`      // The Amazon Resource Name (ARN) of your function.
	FunctionUrl      *string             `json:"FunctionUrl,omitempty"`      // The HTTP URL endpoint for your function.
	InvokeMode       InvokeMode          `json:"InvokeMode,omitempty"`       // Use one of the following options: - `BUFFERED` – This is the default option. Lambda invokes you...
	LastModifiedTime *string             `json:"LastModifiedTime,omitempty"` // When the function URL configuration was last updated, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
}

// FunctionVersionsByCapacityProviderListItem Information about a function version that uses a specific capacity provider, including its ARN an...
type FunctionVersionsByCapacityProviderListItem struct {
	FunctionArn *string `json:"FunctionArn,omitempty"` // The Amazon Resource Name (ARN) of the function version.
	State       State   `json:"State,omitempty"`       // The current state of the function version.
}

// ImageConfig Configuration values that override the container image Dockerfile settings. For more information,...
type ImageConfig struct {
	Command          []string `json:"Command,omitempty"`          // Specifies parameters that you want to pass in with ENTRYPOINT.
	EntryPoint       []string `json:"EntryPoint,omitempty"`       // Specifies the entry point to their application, which is typically the location of the runtime ex...
	WorkingDirectory *string  `json:"WorkingDirectory,omitempty"` // Specifies the working directory.
}

// ImageConfigError Error response to `GetFunctionConfiguration`.
type ImageConfigError struct {
	ErrorCode *string `json:"ErrorCode,omitempty"` // Error code.
	Message   *string `json:"Message,omitempty"`   // Error message.
}

// ImageConfigResponse Response to a `GetFunctionConfiguration` request.
type ImageConfigResponse struct {
	Error       *ImageConfigError `json:"Error,omitempty"`       // Error response to `GetFunctionConfiguration`.
	ImageConfig *ImageConfig      `json:"ImageConfig,omitempty"` // Configuration values that override the container image Dockerfile.
}

// InstanceRequirements Specifications that define the characteristics and constraints for compute instances used by the ...
type InstanceRequirements struct {
	AllowedInstanceTypes  []string       `json:"AllowedInstanceTypes,omitempty"`  // A list of EC2 instance types that the capacity provider is allowed to use. If not specified, all ...
	Architectures         []Architecture `json:"Architectures,omitempty"`         // A list of supported CPU architectures for compute instances. Valid values include `x86_64` and `a...
	ExcludedInstanceTypes []string       `json:"ExcludedInstanceTypes,omitempty"` // A list of EC2 instance types that the capacity provider should not use, even if they meet other r...
}

// InvocationCompletedDetails Details about a function invocation that completed.
type InvocationCompletedDetails struct {
	EndTimestamp   *UnixTimestamp `json:"EndTimestamp,omitempty"`   // The date and time when the invocation ended, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	Error          *EventError    `json:"Error,omitempty"`          // Details about the invocation failure.
	RequestId      *string        `json:"RequestId,omitempty"`      // The request ID for the invocation.
	StartTimestamp *UnixTimestamp `json:"StartTimestamp,omitempty"` // The date and time when the invocation started, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
}

// KafkaSchemaRegistryAccessConfig Specific access configuration settings that tell Lambda how to authenticate with your schema regi...
type KafkaSchemaRegistryAccessConfig struct {
	Type KafkaSchemaRegistryAuthType `json:"Type,omitempty"` // The type of authentication Lambda uses to access your schema registry.
	URI  *string                     `json:"URI,omitempty"`  // The URI of the secret (Secrets Manager secret ARN) to authenticate with your schema registry.
}

// KafkaSchemaRegistryConfig Specific configuration settings for a Kafka schema registry.
type KafkaSchemaRegistryConfig struct {
	AccessConfigs           []KafkaSchemaRegistryAccessConfig `json:"AccessConfigs,omitempty"`           // An array of access configuration objects that tell Lambda how to authenticate with your schema re...
	EventRecordFormat       SchemaRegistryEventRecordFormat   `json:"EventRecordFormat,omitempty"`       // The record format that Lambda delivers to your function after schema validation. - Choose `JSON` ...
	SchemaRegistryURI       *string                           `json:"SchemaRegistryURI,omitempty"`       // The URI for your schema registry. The correct URI format depends on the type of schema registry y...
	SchemaValidationConfigs []KafkaSchemaValidationConfig     `json:"SchemaValidationConfigs,omitempty"` // An array of schema validation configuration objects, which tell Lambda the message attributes you...
}

// KafkaSchemaValidationConfig Specific schema validation configuration settings that tell Lambda the message attributes you wan...
type KafkaSchemaValidationConfig struct {
	Attribute KafkaSchemaValidationAttribute `json:"Attribute,omitempty"` // The attributes you want your schema registry to validate and filter for. If you selected `JSON` a...
}

// LambdaManagedInstancesCapacityProviderConfig Configuration for Lambda-managed instances used by the capacity provider.
type LambdaManagedInstancesCapacityProviderConfig struct {
	CapacityProviderArn                   *string  `json:"CapacityProviderArn,omitempty"`                   // The Amazon Resource Name (ARN) of the capacity provider.
	ExecutionEnvironmentMemoryGiBPerVCpu  *float64 `json:"ExecutionEnvironmentMemoryGiBPerVCpu,omitempty"`  // The amount of memory in GiB allocated per vCPU for execution environments.
	PerExecutionEnvironmentMaxConcurrency *int32   `json:"PerExecutionEnvironmentMaxConcurrency,omitempty"` // The maximum number of concurrent execution environments that can run on each compute instance.
}

// Layer An Lambda layer.
type Layer struct {
	Arn                      *string `json:"Arn,omitempty"`                      // The Amazon Resource Name (ARN) of the function layer.
	CodeSize                 *int64  `json:"CodeSize,omitempty"`                 // The size of the layer archive in bytes.
	SigningJobArn            *string `json:"SigningJobArn,omitempty"`            // The Amazon Resource Name (ARN) of a signing job.
	SigningProfileVersionArn *string `json:"SigningProfileVersionArn,omitempty"` // The Amazon Resource Name (ARN) for a signing profile version.
}

// LayerVersionContentOutput Details about a version of an Lambda layer.
type LayerVersionContentOutput struct {
	CodeSha256               *string `json:"CodeSha256,omitempty"`               // The SHA-256 hash of the layer archive.
	CodeSize                 *int64  `json:"CodeSize,omitempty"`                 // The size of the layer archive in bytes.
	Location                 *string `json:"Location,omitempty"`                 // A link to the layer archive in Amazon S3 that is valid for 10 minutes.
	SigningJobArn            *string `json:"SigningJobArn,omitempty"`            // The Amazon Resource Name (ARN) of a signing job.
	SigningProfileVersionArn *string `json:"SigningProfileVersionArn,omitempty"` // The Amazon Resource Name (ARN) for a signing profile version.
}

// LayerVersionsListItem Details about a version of an Lambda layer.
type LayerVersionsListItem struct {
	CompatibleArchitectures []Architecture `json:"CompatibleArchitectures,omitempty"` // A list of compatible instruction set architectures.
	CompatibleRuntimes      []Runtime      `json:"CompatibleRuntimes,omitempty"`      // The layer's compatible runtimes. The following list includes deprecated runtimes. For more inform...
	CreatedDate             *string        `json:"CreatedDate,omitempty"`             // The date that the version was created, in ISO 8601 format. For example, `2018-11-27T15:10:45.123+...
	Description             *string        `json:"Description,omitempty"`             // The description of the version.
	LayerVersionArn         *string        `json:"LayerVersionArn,omitempty"`         // The ARN of the layer version.
	LicenseInfo             *string        `json:"LicenseInfo,omitempty"`             // The layer's open-source license.
	Version                 *int64         `json:"Version,omitempty"`                 // The version number.
}

// LayersListItem Details about an Lambda layer.
type LayersListItem struct {
	LatestMatchingVersion *LayerVersionsListItem `json:"LatestMatchingVersion,omitempty"` // The newest version of the layer.
	LayerArn              *string                `json:"LayerArn,omitempty"`              // The Amazon Resource Name (ARN) of the function layer.
	LayerName             *string                `json:"LayerName,omitempty"`             // The name of the layer.
}

// LoggingConfig The function's Amazon CloudWatch Logs configuration settings.
type LoggingConfig struct {
	ApplicationLogLevel ApplicationLogLevel `json:"ApplicationLogLevel,omitempty"` // Set this property to filter the application logs for your function that Lambda sends to CloudWatc...
	LogFormat           LogFormat           `json:"LogFormat,omitempty"`           // The format in which Lambda sends your function's application and system logs to CloudWatch. Selec...
	LogGroup            *string             `json:"LogGroup,omitempty"`            // The name of the Amazon CloudWatch log group the function sends logs to. By default, Lambda functi...
	SystemLogLevel      SystemLogLevel      `json:"SystemLogLevel,omitempty"`      // Set this property to filter the system logs for your function that Lambda sends to CloudWatch. La...
}

// OnFailure A destination for events that failed processing. For more information, see Adding a destination.
type OnFailure struct {
	Destination *string `json:"Destination,omitempty"` // The Amazon Resource Name (ARN) of the destination resource. To retain records of failed invocatio...
}

// OnSuccess A destination for events that were processed successfully. To retain records of successful asynch...
type OnSuccess struct {
	Destination *string `json:"Destination,omitempty"` // The Amazon Resource Name (ARN) of the destination resource. Amazon SNS destinations have a messag...
}

// Operation Information about an operation within a durable execution.
type Operation struct {
	CallbackDetails      *CallbackDetails      `json:"CallbackDetails,omitempty"`
	ChainedInvokeDetails *ChainedInvokeDetails `json:"ChainedInvokeDetails,omitempty"`
	ContextDetails       *ContextDetails       `json:"ContextDetails,omitempty"`   // Details about the context, if this operation represents a context.
	EndTimestamp         *UnixTimestamp        `json:"EndTimestamp,omitempty"`     // The date and time when the operation ended, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	ExecutionDetails     *ExecutionDetails     `json:"ExecutionDetails,omitempty"` // Details about the execution, if this operation represents an execution.
	Id                   *string               `json:"Id,omitempty"`               // The unique identifier for this operation.
	Name                 *string               `json:"Name,omitempty"`             // The customer-provided name for this operation.
	ParentId             *string               `json:"ParentId,omitempty"`         // The unique identifier of the parent operation, if this operation is running within a child context.
	StartTimestamp       *UnixTimestamp        `json:"StartTimestamp,omitempty"`   // The date and time when the operation started, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZD).
	Status               OperationStatus       `json:"Status,omitempty"`           // The current status of the operation.
	StepDetails          *StepDetails          `json:"StepDetails,omitempty"`      // Details about the step, if this operation represents a step.
	SubType              *string               `json:"SubType,omitempty"`          // The subtype of the operation, providing additional categorization.
	Type                 OperationType         `json:"Type,omitempty"`             // The type of operation.
	WaitDetails          *WaitDetails          `json:"WaitDetails,omitempty"`      // Details about the wait operation, if this operation represents a wait.
}

// ProvisionedConcurrencyConfigListItem Details about the provisioned concurrency configuration for a function alias or version.
type ProvisionedConcurrencyConfigListItem struct {
	AllocatedProvisionedConcurrentExecutions *int32                           `json:"AllocatedProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency allocated. When a weighted alias is used during linear and ...
	AvailableProvisionedConcurrentExecutions *int32                           `json:"AvailableProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency available.
	FunctionArn                              *string                          `json:"FunctionArn,omitempty"`                              // The Amazon Resource Name (ARN) of the alias or version.
	LastModified                             *string                          `json:"LastModified,omitempty"`                             // The date and time that a user last updated the configuration, in ISO 8601 format.
	RequestedProvisionedConcurrentExecutions *int32                           `json:"RequestedProvisionedConcurrentExecutions,omitempty"` // The amount of provisioned concurrency requested.
	Status                                   ProvisionedConcurrencyStatusEnum `json:"Status,omitempty"`                                   // The status of the allocation process.
	StatusReason                             *string                          `json:"StatusReason,omitempty"`                             // For failed allocations, the reason that provisioned concurrency could not be allocated.
}

// ProvisionedPollerConfig The provisioned mode configuration for the event source. Use Provisioned Mode to customize the mi...
type ProvisionedPollerConfig struct {
	MaximumPollers  *int32  `json:"MaximumPollers,omitempty"`  // The maximum number of event pollers this event source can scale up to. For Amazon SQS events sour...
	MinimumPollers  *int32  `json:"MinimumPollers,omitempty"`  // The minimum number of event pollers this event source can scale down to. For Amazon SQS events so...
	PollerGroupName *string `json:"PollerGroupName,omitempty"` // (Amazon MSK and self-managed Apache Kafka) The name of the provisioned poller group. Use this opt...
}

// RetryDetails Information about retry attempts for an operation.
type RetryDetails struct {
	CurrentAttempt          *int32 `json:"CurrentAttempt,omitempty"`          // The current attempt number for this operation.
	NextAttemptDelaySeconds *int32 `json:"NextAttemptDelaySeconds,omitempty"` // The delay before the next retry attempt, in seconds.
}

// RuntimeVersionConfig The ARN of the runtime and any errors that occured.
type RuntimeVersionConfig struct {
	Error             *RuntimeVersionError `json:"Error,omitempty"`             // Error response when Lambda is unable to retrieve the runtime version for a function.
	RuntimeVersionArn *string              `json:"RuntimeVersionArn,omitempty"` // The ARN of the runtime version you want the function to use.
}

// RuntimeVersionError Any error returned when the runtime version information for the function could not be retrieved.
type RuntimeVersionError struct {
	ErrorCode *string `json:"ErrorCode,omitempty"` // The error code.
	Message   *string `json:"Message,omitempty"`   // The error message.
}

// ScalingConfig (Amazon SQS only) The scaling configuration for the event source. To remove the configuration, pa...
type ScalingConfig struct {
	MaximumConcurrency *int32 `json:"MaximumConcurrency,omitempty"` // Limits the number of concurrent instances that the Amazon SQS event source can invoke.
}

// SelfManagedEventSource The self-managed Apache Kafka cluster for your event source.
type SelfManagedEventSource struct {
	Endpoints map[string]string `json:"Endpoints,omitempty"` // The list of bootstrap servers for your Kafka brokers in the following format: `"KAFKA_BOOTSTRAP_S...
}

// SelfManagedKafkaEventSourceConfig Specific configuration settings for a self-managed Apache Kafka event source.
type SelfManagedKafkaEventSourceConfig struct {
	ConsumerGroupId      *string                    `json:"ConsumerGroupId,omitempty"`      // The identifier for the Kafka consumer group to join. The consumer group ID must be unique among a...
	SchemaRegistryConfig *KafkaSchemaRegistryConfig `json:"SchemaRegistryConfig,omitempty"` // Specific configuration settings for a Kafka schema registry.
}

// SnapStartResponse The function's SnapStart setting.
type SnapStartResponse struct {
	ApplyOn            SnapStartApplyOn            `json:"ApplyOn,omitempty"`            // When set to `PublishedVersions`, Lambda creates a snapshot of the execution environment when you ...
	OptimizationStatus SnapStartOptimizationStatus `json:"OptimizationStatus,omitempty"` // When you provide a qualified Amazon Resource Name (ARN), this response element indicates whether ...
}

// SourceAccessConfiguration To secure and define access to your event source, you can specify the authentication protocol, VP...
type SourceAccessConfiguration struct {
	Type SourceAccessType `json:"Type,omitempty"` // The type of authentication protocol, VPC components, or virtual host for your event source. For e...
	URI  *string          `json:"URI,omitempty"`  // The value for your chosen configuration in `Type`. For example: `"URI": "arn:aws:secretsmanager:u...
}

// StepDetails Details about a step operation.
type StepDetails struct {
	Attempt              *int32         `json:"Attempt,omitempty"`              // The current attempt number for this step.
	Error                *ErrorObject   `json:"Error,omitempty"`                // Details about the step failure.
	NextAttemptTimestamp *UnixTimestamp `json:"NextAttemptTimestamp,omitempty"` // The date and time when the next attempt is scheduled, in ISO-8601 format (YYYY-MM-DDThh:mm:ss.sTZ...
	Result               *string        `json:"Result,omitempty"`               // The JSON response payload from the step operation.
}

// StepFailedDetails Details about a step that failed.
type StepFailedDetails struct {
	Error        *EventError   `json:"Error,omitempty"`        // Details about the step failure.
	RetryDetails *RetryDetails `json:"RetryDetails,omitempty"` // Information about retry attempts for this step operation.
}

// StepStartedDetails Details about a step that has started.
type StepStartedDetails struct{}

// StepSucceededDetails Details about a step that succeeded.
type StepSucceededDetails struct {
	Result       *EventResult  `json:"Result,omitempty"`       // The response payload from the successful operation.
	RetryDetails *RetryDetails `json:"RetryDetails,omitempty"` // Information about retry attempts for this step operation.
}

// TagsError An object that contains details about an error related to retrieving tags.
type TagsError struct {
	ErrorCode *string `json:"ErrorCode,omitempty"` // The error code.
	Message   *string `json:"Message,omitempty"`   // The error message.
}

// TargetTrackingScalingPolicy A scaling policy for the capacity provider that automatically adjusts capacity to maintain a targ...
type TargetTrackingScalingPolicy struct {
	PredefinedMetricType CapacityProviderPredefinedMetricType `json:"PredefinedMetricType,omitempty"` // The predefined metric type to track for scaling decisions.
	TargetValue          *float64                             `json:"TargetValue,omitempty"`          // The target value for the metric that the scaling policy attempts to maintain through scaling acti...
}

// TenancyConfig Specifies the tenant isolation mode configuration for a Lambda function. This allows you to confi...
type TenancyConfig struct {
	TenantIsolationMode TenantIsolationMode `json:"TenantIsolationMode,omitempty"` // Tenant isolation mode allows for invocation to be sent to a corresponding execution environment d...
}

// TraceHeader Contains trace headers for the Lambda durable execution.
type TraceHeader struct {
	XAmznTraceId *string `json:"XAmznTraceId,omitempty"` // The X-Ray trace header associated with the durable execution.
}

// TracingConfigResponse The function's X-Ray tracing configuration.
type TracingConfigResponse struct {
	Mode TracingMode `json:"Mode,omitempty"` // The tracing mode.
}

// VpcConfigResponse The VPC security groups and subnets that are attached to a Lambda function.
type VpcConfigResponse struct {
	Ipv6AllowedForDualStack *bool    `json:"Ipv6AllowedForDualStack,omitempty"` // Allows outbound IPv6 traffic on VPC functions that are connected to dual-stack subnets.
	SecurityGroupIds        []string `json:"SecurityGroupIds,omitempty"`        // A list of VPC security group IDs.
	SubnetIds               []string `json:"SubnetIds,omitempty"`               // A list of VPC subnet IDs.
	VpcId                   *string  `json:"VpcId,omitempty"`                   // The ID of the VPC.
}

// WaitCancelledDetails Details about a wait operation that was cancelled.
type WaitCancelledDetails struct {
	Error *EventError `json:"Error,omitempty"` // Details about why the wait operation was cancelled.
}

// WaitDetails Details about a wait operation.
type WaitDetails struct {
	ScheduledEndTimestamp *UnixTimestamp `json:"ScheduledEndTimestamp,omitempty"` // The date and time when the wait operation is scheduled to complete, in ISO-8601 format (YYYY-MM-D...
}

// WaitStartedDetails Details about a wait operation that has started.
type WaitStartedDetails struct {
	Duration              *int32         `json:"Duration,omitempty"`              // The duration to wait, in seconds.
	ScheduledEndTimestamp *UnixTimestamp `json:"ScheduledEndTimestamp,omitempty"` // The date and time when the wait operation is scheduled to complete, in ISO-8601 format (YYYY-MM-D...
}

// WaitSucceededDetails Details about a wait operation that succeeded.
type WaitSucceededDetails struct {
	Duration *int32 `json:"Duration,omitempty"` // The wait duration, in seconds.
}
