package reporter

import (
	"bytes"
	"fmt"
	"strings"
	"text/template"

	"github.com/robmorgan/infraspec/tools/cloudmirror/internal/models"
)

// MarkdownReporter generates Markdown reports
type MarkdownReporter struct{}

// NewMarkdownReporter creates a new Markdown reporter
func NewMarkdownReporter() *MarkdownReporter {
	return &MarkdownReporter{}
}

const singleServiceTemplate = `# CloudMirror Parity Report

## {{.ServiceFullName}}

| Metric | Value |
|--------|-------|
| **Service** | {{.ServiceName}} |
| **API Version** | {{.APIVersion}} |
| **Protocol** | {{.Protocol}} |
| **Coverage** | {{printf "%.1f" .CoveragePercent}}% ({{len .Supported}}/{{.NonDeprecatedTotal}}) |
| **Total Operations** | {{.TotalOperations}} |
| **Deprecated** | {{len .Deprecated}} |

---

## Supported Operations ({{len .Supported}})

{{if .Supported}}
| Operation | Handler | File | Priority |
|-----------|---------|------|----------|
{{range .Supported}}| {{.Name}} | {{.Handler}} | {{.File}}:{{.Line}} | {{priorityEmoji .Priority}} {{.Priority}} |
{{end}}
{{else}}
_No operations implemented yet._
{{end}}

---

## Missing Operations ({{len .Missing}})

{{if .Missing}}
### High Priority
{{range .Missing}}{{if eq .Priority "high"}}
- **{{.Name}}**{{if .Documentation}}: {{truncate .Documentation 100}}{{end}}
{{end}}{{end}}

### Medium Priority
{{range .Missing}}{{if eq .Priority "medium"}}
- **{{.Name}}**{{if .Documentation}}: {{truncate .Documentation 100}}{{end}}
{{end}}{{end}}

### Low Priority
{{range .Missing}}{{if eq .Priority "low"}}
- {{.Name}}{{if .Documentation}}: {{truncate .Documentation 100}}{{end}}
{{end}}{{end}}
{{else}}
_All non-deprecated operations are implemented!_
{{end}}

{{if .Deprecated}}
---

## Deprecated Operations ({{len .Deprecated}})

| Operation | Implemented | Message |
|-----------|-------------|---------|
{{range .Deprecated}}| {{.Name}} | {{if .Implemented}}Yes{{else}}No{{end}} | {{.DeprecatedMsg}} |
{{end}}
{{end}}

---

_Generated by CloudMirror on {{.GeneratedAt.Format "2006-01-02 15:04:05 UTC"}}_
`

const multiServiceTemplate = `# CloudMirror Parity Report

## Summary

| Metric | Value |
|--------|-------|
| **Services Analyzed** | {{len .Services}} |
| **Total Operations** | {{.TotalOperations}} |
| **Supported** | {{.TotalSupported}} |
| **Missing** | {{.TotalMissing}} |
| **Overall Coverage** | {{printf "%.1f" .OverallCoverage}}% |

---

## Service Coverage

| Service | Coverage | Supported | Missing | Deprecated |
|---------|----------|-----------|---------|------------|
{{range .Services}}| {{.ServiceName}} | {{printf "%.1f" .CoveragePercent}}% | {{len .Supported}} | {{len .Missing}} | {{len .Deprecated}} |
{{end}}

---

{{range .Services}}
## {{.ServiceFullName}} ({{.ServiceName}})

**Coverage:** {{printf "%.1f" .CoveragePercent}}% ({{len .Supported}}/{{nonDeprecatedTotal .}})

{{if .Supported}}
### Supported ({{len .Supported}})
{{range .Supported}}- {{.Name}}
{{end}}
{{end}}

{{if .Missing}}
### Missing - High Priority
{{range .Missing}}{{if eq .Priority "high"}}- {{.Name}}
{{end}}{{end}}
{{end}}

---

{{end}}

_Generated by CloudMirror on {{.GeneratedAt.Format "2006-01-02 15:04:05 UTC"}}_
`

const diffTemplate = `# CloudMirror API Diff Report

## {{.ServiceName}}

**Version Change:** {{.OldVersion}} → {{.NewVersion}}

{{if .NewOperations}}
### New Operations ({{len .NewOperations}})

These operations were added to the AWS API:

{{range .NewOperations}}- {{.}}
{{end}}
{{end}}

{{if .RemovedOperations}}
### Removed Operations ({{len .RemovedOperations}})

These operations were removed from the AWS API:

{{range .RemovedOperations}}- {{.}}
{{end}}
{{end}}

{{if .ChangedOperations}}
### Changed Operations ({{len .ChangedOperations}})

{{range .ChangedOperations}}
#### {{.Name}}
{{range .Changes}}- {{.}}
{{end}}
{{end}}
{{end}}

{{if and (not .NewOperations) (not .RemovedOperations) (not .ChangedOperations)}}
_No changes detected between versions._
{{end}}
`

// GenerateReport generates a Markdown report for a single service
func (r *MarkdownReporter) GenerateReport(report *models.CoverageReport) ([]byte, error) {
	tmpl, err := template.New("report").Funcs(templateFuncs()).Parse(singleServiceTemplate)
	if err != nil {
		return nil, err
	}

	// Add computed field
	type reportWithComputed struct {
		*models.CoverageReport
		NonDeprecatedTotal int
	}

	data := reportWithComputed{
		CoverageReport:     report,
		NonDeprecatedTotal: report.TotalOperations - len(report.Deprecated),
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// GenerateMultiReport generates a Markdown report for multiple services
func (r *MarkdownReporter) GenerateMultiReport(multi *models.MultiServiceReport) ([]byte, error) {
	tmpl, err := template.New("multi").Funcs(templateFuncs()).Parse(multiServiceTemplate)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, multi); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

// GenerateDiffReport generates a Markdown report for version differences
func (r *MarkdownReporter) GenerateDiffReport(diff *models.VersionDiff) ([]byte, error) {
	tmpl, err := template.New("diff").Parse(diffTemplate)
	if err != nil {
		return nil, err
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, diff); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func templateFuncs() template.FuncMap {
	return template.FuncMap{
		"priorityEmoji": func(p models.Priority) string {
			switch p {
			case models.PriorityHigh:
				return "🔴"
			case models.PriorityMedium:
				return "🟡"
			case models.PriorityLow:
				return "🟢"
			default:
				return "⚪"
			}
		},
		"truncate": func(s string, maxLen int) string {
			if len(s) <= maxLen {
				return s
			}
			return s[:maxLen-3] + "..."
		},
		"nonDeprecatedTotal": func(r *models.CoverageReport) int {
			return r.TotalOperations - len(r.Deprecated)
		},
		"eq": func(a, b interface{}) bool {
			return fmt.Sprintf("%v", a) == fmt.Sprintf("%v", b)
		},
	}
}

// GenerateGitHubIssueBody generates markdown suitable for a GitHub issue
func (r *MarkdownReporter) GenerateGitHubIssueBody(diff *models.VersionDiff, report *models.CoverageReport) string {
	var sb strings.Builder

	sb.WriteString("## AWS API Changes Detected\n\n")
	sb.WriteString(fmt.Sprintf("**Service:** %s\n", diff.ServiceName))
	sb.WriteString(fmt.Sprintf("**Current Coverage:** %.1f%%\n\n", report.CoveragePercent))

	if len(diff.NewOperations) > 0 {
		sb.WriteString("### New AWS Operations\n\n")
		sb.WriteString("The following operations were added to the AWS API and should be considered for implementation:\n\n")
		for _, op := range diff.NewOperations {
			sb.WriteString(fmt.Sprintf("- [ ] `%s`\n", op))
		}
		sb.WriteString("\n")
	}

	if len(diff.RemovedOperations) > 0 {
		sb.WriteString("### Removed AWS Operations\n\n")
		sb.WriteString("The following operations were removed from the AWS API:\n\n")
		for _, op := range diff.RemovedOperations {
			sb.WriteString(fmt.Sprintf("- `%s`\n", op))
		}
		sb.WriteString("\n")
	}

	if len(diff.ChangedOperations) > 0 {
		sb.WriteString("### Changed Operations\n\n")
		for _, op := range diff.ChangedOperations {
			sb.WriteString(fmt.Sprintf("#### %s\n", op.Name))
			for _, change := range op.Changes {
				sb.WriteString(fmt.Sprintf("- %s\n", change))
			}
			sb.WriteString("\n")
		}
	}

	sb.WriteString("---\n")
	sb.WriteString("*Generated by CloudMirror*\n")

	return sb.String()
}
