name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]
  workflow_call:

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: read # this can be 'read' if the signatures are in remote repository
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # the below token should have repo scope and must be manually added by you in the repository's secret
          # This token is required only if you have configured to store the signatures in a remote repository/organization
          PERSONAL_ACCESS_TOKEN: ${{ secrets.INFRASPEC_GITHUB_BREW_TOKEN }}
        with:
          path-to-signatures: "infraspec/cla-signatures.json"
          path-to-document: "https://github.com/robmorgan/infraspec/blob/main/website/src/app/dev/cla.mdx"
          # branch should not be protected
          branch: "main"
          remote-organization-name: "robmorgan"
          remote-repository-name: "infraspec-cla-signatures"
          allowlist: github-actions[bot],dependabot[bot]
