name: Lint Gherkin Files

on:
  pull_request:
    paths:
      - "features/**/*.feature"
  push:
    paths:
      - "features/**/*.feature"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint Gherkin files
        run: npm run lint:gherkin
